### PR TITLE
Bump QGIS version to 3.18.0

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gillins** [comment]
@SrNetoChan I'm hoping that we don't need any of these patches now:

- Patch 0001 doesn't do anything anymore since https://github.com/qgis/QGIS/pull/9300 reorganised the code to do the right thing for all non-OSX platforms.
- Patch 0002 is no longer needed as the version of Qt we use now ships a `pyrcc5.bat` (the older Qt 5.9 didn't)
- Patch 0003 fixed by https://github.com/qgis/QGIS/pull/41346
- Patch 0004 fixed by https://github.com/qgis/QGIS/pull/41307 (but needs QGIS_INSTALL_SYS_LIBS=FALSE passed to cmake on Windows)
- Patch 0005 I think this is no longer necessary 
- Patch 0006 fixed by https://github.com/qgis/QGIS/pull/41323
- Patch 0007 fixed by https://github.com/qgis/QGIS/pull/41001 and https://github.com/qgis/QGIS/pull/41207

So I think if you remove all these patches (and pass `-D QGIS_INSTALL_SYS_LIBS=FALSE` to `cmake` on Windows) it should all compile.... hopefully. Let me know how this goes, unfortunately I won't be able to help for a couple of days at least but I'll try and keep an eye on this - ping me if there are problems.

**Comment by SrNetoChan** [comment]
Please, don't merge yet, I will try to add pdal for point_cloud support.

@gillins @ocefpaf where can I find instructions to build the recipe locally on linux using docker.

**Comment by SrNetoChan** [comment]
Actually, maybe it's better to merge now, have a working build, and then calmly work on adding pdal support.

**Comment by gillins** [comment]
@nyalldawson we are now building qgis successfully for all platforms without any patches! Thanks heaps for your help with this 😀

**Comment by nyalldawson** [comment]
@gillins all I did was merge your hard work -- the thanks belong to you!

**Pull request merged**
