### PR TITLE
Test geos 351

### PR DESCRIPTION
**Pull request by ocefpaf**
Also fixed a copy-n-pasta from my last PR.

### CODE REVIEW

**Comment by ceholden** [comment]
Odd error at 98% of the build:
``` bash
[ 98%] Generating ui_dialogAbout.py
Traceback (most recent call last):
  File "../../../../../scripts/pyuic-wrapper.py", line 26, in <module>
    import qgis.PyQt.uic.pyuic
  File "/feedstock_root/build_artefacts/work/qgis-2.18.0/build/output/python/qgis/__init__.py", line 27, in <module>
    from qgis.core import QgsFeature, QgsGeometry
  File "/feedstock_root/build_artefacts/work/qgis-2.18.0/build/output/python/qgis/core/__init__.py", line 30, in <module>
    from qgis._core import *
ImportError: libproj.so.9: cannot open shared object file: No such file or directory
make[2]: *** [python/plugins/GdalTools/tools/ui_dialogAbout.py] Error 1
make[1]: *** [python/plugins/GdalTools/tools/CMakeFiles/zzz-GdalTools-2-depend.dir/all] Error 2
make: *** [all] Error 2
Command failed: /bin/bash -x -e /feedstock_root/build_artefacts/work/qgis-2.18.0/conda_build.sh

./ci_support/run_docker_build.sh returned exit code 1
```

Looks like `proj.4` and `proj4` were both installed:
``` bash
 156     proj.4-4.9.3               |                0         1.3 MB  conda-forge
 157     proj4-4.9.3                |                0         1.3 MB  conda-forge
```

Also found this:
``` bash
2509 [ 66%] Linking CXX executable ../../output/bin/crssync
2510 /opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: warning: libproj.so.9, needed by /opt/conda/envs/_build_placehold_placehold_pl     acehold_placehold_placehold_placeho/lib/libgdal.so, not found (try using -rpath or -rpath-link)
2511 /opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: warning: libgeos-3.4.2.so, needed by /opt/conda/envs/_build_placehold_placehol     d_placehold_placehold_placehold_placeho/lib/libspatialite.so, not found (try using -rpath or -rpath-link)
```

Not sure why both `proj4`/`proj.4` were installed, but seems like `libspatialite.so` still expects the older GEOS.

**Comment by ocefpaf** [comment]
This is not ready yet @ceholden. There is also a `gdal` with `geos 3.5.1` next. I just left it here as a place holder so I do not forget :grimacing:

**Comment by ocefpaf** [comment]
@ceholden with the new `libspatialite` and `gdal` packages on the channel this is now passing. Can you take a quick look and merge if you agree with the changes?

**Comment by ceholden** [comment]
Looks good! :+1:

**Pull request merged**
