### PR TITLE
Update LTR to 3.10.8

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@ocefpaf there's something strange with osx builds. Only one is passing.

I wonder, should we merge this to get linux and windows rolling, and the create a new PR to take care of OSX?

**Comment by SrNetoChan** [comment]
@ocefpaf there's something strange with osx builds. Only one is passing.

I wonder, should we merge this to get linux and windows rolling, and the create a new PR to take care of OSX?

**Comment by ocefpaf** [comment]
Let me ask @isuruf for help very quick first. He knows more about the changes in the macOS sdk and may know what is going on.

**Comment by SrNetoChan** [comment]
OSX has been acting strange since last release. It seems to fail randomly, and pass later without issues. Could it be related to something outside this feedstock?

**Comment by SrNetoChan** [comment]
@isuruf can you please explain what was the black magic you did?

**Comment by SrNetoChan** [comment]
The failure now seems related to some kind of time out. Is it possible to retrigger the build just for the failing one?

**Comment by ocefpaf** [comment]
@conda-forge-admin, please restart ci

**Comment by SrNetoChan** [comment]
@ocefpaf @isuruf sometimes it's python 3.6 that fails, other times is 3.7. But they all break in the same exact place.

Just to improve my knowledge about how all this works. Given the current tests status, if we merge, will this cause that python 3.6 for osx would not be available on condo? Are the built binaries automatically used, or is there another system rebuilding them and uploading it to the coda-forge channel?

**Comment by ocefpaf** [comment]
> Just to improve my knowledge about how all this works. Given the current tests status, if we merge, will this cause that python 3.6 for osx would not be available on conda?

Yep.

> Are the built binaries automatically used, or is there another system rebuilding them and uploading it to the conda-forge channel in anaconda?

They are rebuilt on master for the upload, the ones here on the CIs are not. (Unless you don't do a fork which is frowned upon.)

Let's merge and I'll try to restart the CIs on master to get the failing one to pass.

**Comment by SrNetoChan** [comment]
> > Just to improve my knowledge about how all this works. Given the current tests status, if we merge, will this cause that python 3.6 for osx would not be available on conda?
> 
> Yep.
> 
> > Are the built binaries automatically used, or is there another system rebuilding them and uploading it to the conda-forge channel in anaconda?
> 
> They are rebuilt on master for the upload, the ones here on the CIs are not. (Unless you don't do a fork which is frowned upon.)
> 
> Let's merge and I'll try to restart the CIs on master to get the failing one to pass.
> 
> 

Thanks @ocefpaf for explaining.

**Comment by SrNetoChan** [comment]
@ocefpaf although Linux builds were working fine here, they did not land on Anaconda Cloud after the merge. Any idea of what could have happened?

**Comment by ocefpaf** [comment]
Looks like a time-out error. Restarting it ...

**Comment by ocefpaf** [comment]
The CIs passed on master now but the packages are still no available. I'm familiar with the new staging process, maybe it takes longer, maybe it does not work with master re-starts. @beckermr do you know what is going on?

**Comment by ocefpaf** [comment]
All CIs passed the restart but packages seems to be still stuck ad cf-staging. See https://anaconda.org/cf-staging/qgis/files?version=

Trying one more restart...

**Comment by beckermr** [comment]
I'd check the job. Those packages were uploaded two days ago. It should delete them.

**Comment by beckermr** [comment]
I think the copy worked fine: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=191480&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412&l=11240

**Comment by beckermr** [comment]
I am guessing the hashes changed.

**Comment by beckermr** [comment]
wait wrong version...

**Comment by ocefpaf** [comment]
> wait wrong version...

Yep. I also restart the wrong branch :-/

It should work now.

**Comment by ocefpaf** [comment]
Yep. All good now: https://anaconda.org/conda-forge/qgis/files?version=3.10.8

Sorry for the delay @SrNetoChan. I completely forgot that this was the LTR branch and kept restarting and watching master :-/

**Comment by SrNetoChan** [comment]
@ocefpaf please don't ask for sorry. Thanks for all your work!

**Pull request merged**
