### PR TITLE
update QGIS stable to 3.14.15

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
It needs pinning on GDAL 3.0

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@ocefpaf @m-kuhn  I have added a local configuration file. For now it's just pinning proj and gdal, but my goal, in the future, is to pin our main dependencies for all patch releases. 

So when 3.16.0 is out, I will remove the local pinning and see what Conda-forge suggests for all dependencies. after we get it working, I will re-add the local configuration file with the list of main working dependencies. This way, when 3.16.1 arrives, we force it to use the same dependencies.

**Comment by SrNetoChan** [comment]
@m-kuhn what would be you suggested dependencies for pinning?

**Comment by m-kuhn** [comment]
Good move!

What's the idea to keep the different versions in parallel?

 - branches for latest and ltr?
 - repositories for latest and ltr?
 - something else?

**Comment by SrNetoChan** [comment]
> Good move!
> 
> What's the idea to keep the different versions in parallel?
> 
> * branches for latest and ltr?
> * repositories for latest and ltr?
> * something else?

the same as we are doing now. it's branches for LTR and latest stable (master branch), different pinning files. We need to decide if we want to pin to major or minor version.

**Comment by m-kuhn** [comment]
> > Good move!
> > What's the idea to keep the different versions in parallel?
> > 
> > * branches for latest and ltr?
> > * repositories for latest and ltr?
> > * something else?
> 
> the same as we are doing now. it's branches for LTR and latest stable (master branch), different pinning files. We need to decide if we want to pin to major or minor version.

Proj: major, gdal minor, qt minor?

**Comment by SrNetoChan** [comment]
@m-kuhn said:
> Proj: major, gdal minor, qt minor?

Sounds good to me. Any other dependencies? GEOS, Spatialite?

**Comment by m-kuhn** [comment]
geos (major) sounds like a good candidate too.
No strong opinion on spatialite.
I would also expect that there are some dependencies defined through other pinned packages (e.g. the pinned gdal version will be built against a specific spatialite version), or does that not work this way?

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please restart ci

**Comment by SrNetoChan** [comment]
@ocefpaf I have restarted ci, if we get similar results (mixed failures, only some   builds are failing for the same platform) should we merge as is, and the restart ci on master?

**Comment by SrNetoChan** [comment]
@m-kuhn said:
> geos (major) sounds like a good candidate too.
> No strong opinion on spatialite.
> I would also expect that there are some dependencies defined through other pinned packages (e.g. the pinned gdal version will be built against a specific spatialite version), or does that not work this way?

I think it does. But I am unaware of cross dependencies.

 I will try to keep all dependencies on qgis about as pinned as possible. Starting on QGIS 3.16.

**Comment by m-kuhn** [comment]
I was going to write geos minor. Looking forward to seeing how that works!

**Comment by SrNetoChan** [comment]
@ocefpaf @gillins Any ideias? It always fails only on Windows, only on python 3.7 and 3.8. It complains about missing files during the build, but it's not always the same file. My gut filling is that it could be something related to disk space.

**Comment by gillins** [comment]
It's still got the `sip` build path hardcoded (`D:\bld\sip_1597330487187\_h_env\Library\bin\sip`). I thought this was fixed? Any ideas @isuruf ?

**Comment by isuruf** [comment]
There was a new sip release which is also broken on windows. Can you send a PR to https://github.com/conda-forge/admin-requests to mark the windows builds of sip for 4.19.24 as broken?

**Comment by ocefpaf** [comment]
> There was a new sip release which is also broken on windows. Can you send a PR to [conda-forge/admin-requests](https://github.com/conda-forge/admin-requests) to mark the windows builds of sip for 4.19.24 as broken?

Argh! We still don't have a working conda-build I guess. I'll do that.

**Comment by SrNetoChan** [comment]
@ocefpaf  Although the builds all have passed here. Some seem to be failing in the final build that uploads the packages to condacloud:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=198778&view=results

**Comment by SrNetoChan** [comment]
No Module Name PyQt5

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=198778&view=logs&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=0bf03e01-0bec-5b85-5316-b1633322e895&l=4958

**Pull request merged**
