### PR TITLE
Update LTR 3.16.10

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [X ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@gillins thanks for your efforts. it feels strange that only mac and linux are somehow missing some include, but not windows. Could the building scripts be somehow different?

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@gillins qwt was the culprit. Windows was using version 6.1, while linux and mac were trying to use 6.2. 

I didn't find this by myself, it was a hint from @jef-n.

Since this is an LTR branch, I have pinned qwt version, it seems that this should have been fixed in QGIs master already.

https://github.com/qgis/QGIS/commit/6f9cbde7c782274ebe5875da7dbac98d68e9827b

**Comment by gillins** [comment]
Wow thanks @SrNetoChan @jef-n ! I never would have picked that up. Great to get something building ATM...

**Comment by SrNetoChan** [comment]
For LTR, this is something I will definitely start to check when in trouble,  Differences in dependencies versions.

Thanks for your efforts to fixing it before.

**Pull request merged**
