### PR TITLE
Bump to Qt version to 5.14

### PR DESCRIPTION
**Pull request by m-kuhn**
I doubt it's the right way to do things, but I'll just try anyway. Let me know if I better do that differently.

### CODE REVIEW

**Comment by gillins** [comment]
Hi @m-kuhn pinning is done globally for all conda forge packages (see https://conda-forge.org/docs/maintainer/pinning_deps.html). There will be an automated process updating packages to a newer `qt` when it is ready.

BTW the latest version of `qt` in conda-forge is 5.12.5. If you need a later version maybe you could submit a PR to the `qt` feedstock with an update to 5.14?

**Comment by m-kuhn** [comment]
Thank you @gillins I'll have a look into upgrading qt.

Slightly off topic, but still curious: there is a qgis long term release (patch releases each month) and this should preferably always be shipped with qt lts versions. Then this needs a qt-lts package as well as lts packages for all the qt reverse dependencies. Or is that a concept that would need to live outside conda-forge?

**Comment by kmuehlbauer** [comment]
@m-kuhn There is the LTR branch in this feedstock which handles the LTR releases.

**Comment by SrNetoChan** [comment]
For QGIS LTS, what's the preferable way to pin specific dependences?

**Comment by m-kuhn** [comment]
For reference https://github.com/conda-forge/qt-feedstock/pull/152

**Comment by gillins** [comment]
I think pinning has to be done globally otherwise we end up with software combinations that can't be installed into the same environment. So we probably don't want to pin LTS software different from anything else.

Is this right @ocefpaf ?

**Comment by SrNetoChan** [comment]
Well, if we want to give support to LTS versions, we need to be able to pin dependencies for those cases, because LTS versions won't probably work with the most recent versions of every dependency.
I was under the impression that we could pin versions in the recipe or in a "local" config file.

**Comment by ocefpaf** [comment]
You are both correct. The pinning is applied globally but we can have a local `conda_build_config.yaml` file with an override for special cases like this one.

It seems that the case here is that you want to use a newer Qt from the global pin, right? We need to build that one first and then start a migration/global pin update.

**Comment by SrNetoChan** [comment]
When you say migration-gloabl pin update, you mean rebuilding everything with the new dependency version?

**Comment by m-kuhn** [comment]
> It seems that the case here is that you want to use a newer Qt from the global pin, right? We need to build that one first and then start a migration/global pin update.

Right now yes. But in general it will be vice versa: ship qgis-3.10.x for a year with the same (major) dependency versions even if global moves forward.

**Comment by SrNetoChan** [comment]
@ocefpaf where should the local conda_build_config.yaml file be placed? Next to the recipe?

**Comment by ocefpaf** [comment]
> @ocefpaf where should the local conda_build_config.yaml file be placed? Next to the recipe?

In the recipe folder. Here is an example of a package that we build for two versions of `gdal`: https://github.com/conda-forge/rasterio-feedstock/blob/master/recipe/conda_build_config.yaml

**Pull request closed without merging**
