### PR TITLE
Ltr 3.22

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Updates the LTR branch to follow the 3.22.x version
Bumps version to 3.22.13
Try to pin main dependencies to use same major versions as 3.22.11 (If possible they should be pinned for all the patches of a specific LTR version)

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@gillins I wonder why Python 3.11 wasn't considered in here. Is it normal?

**Comment by SrNetoChan** [comment]
On windows if fails on test while looking for a PROJ_DATA env variable. In the code, I can only find setting PROJ_Lib directly. Not sure if it's the recipe that is outdated or the test.

**Comment by gillins** [comment]
What version of proj are you using? It's PROJ_DATA in the latest but PROJ_LIB in earlier versions

**Comment by SrNetoChan** [comment]
> What version of proj are you using? It's PROJ_DATA in the latest but PROJ_LIB in earlier versions 

It's pinned to 9.0. It worked for 3.22.11.

**Comment by SrNetoChan** [comment]
In the post_link.bat we still only have this. No mention to PROJ_DATA

set "PROJ_LIB=%LIBRARY_PREFIX%\share\proj"

**Comment by SrNetoChan** [comment]
Also seems that there are some patches leftovers in this branch, so I should compare it with main.

BTW, we seem to have a main and a master branch, should we eliminate master?

**Comment by gillins** [comment]
This is the change that introduced PROJ_DATA (https://github.com/conda-forge/proj.4-feedstock/commit/e878f9a4bcd02af30b6bbf781441a535f0c24dba). Didn't realize we also had this in post_link.bat, that definitely didn't get set with latest pinnings, not sure what's going on...
Yes we can eliminate master, very confusing!

**Comment by gillins** [comment]
BTW post-link.bat only run once after installation (https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html) to run `qgis` with the `--postinstall` option (not sure what this does). So it doesn't set these variables permanently. We should probably check that this step is still required and update these vars....

**Comment by SrNetoChan** [comment]
But, testing is done with an installation, isn't it?

**Comment by gillins** [comment]
AFAICT the variables on `post-link.bat` are only set while that script is running (does `qgis --postinstall` need these set?). I don't think that are 'sourced' into the current session like activate.bat etc.
Anyway, post-link.bat only run once (right after install) where everything else is set every time the environment is activated (like when the test environment is created).

**Comment by SrNetoChan** [comment]
Starting over...

**Pull request closed without merging**
