### PR TITLE
add linux_ppc64le

### PR DESCRIPTION
**Pull request by gillins**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@conda-forge/help-ppc64le any thoughts about the following error?:
```
FAILED: output/python/qgis/_core.so 
: && $BUILD_PREFIX/bin/powerpc64le-conda-linux-gnu-c++ -fPIC -fvisibility-inlines-hidden -fmessage-length=0 -mcpu=power8 -mtune=power8 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/qgis-3.28.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wnon-virtual-dtor -Wno-redundant-move -Wno-misleading-indentation -Wno-deprecated-copy -O3 -DNDEBUG  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib -Wl,-rpath-link,$BUILD_PREFIX/powerpc64le-conda-linux-gnu/sysroot -Wl,--no-undefined -shared  -o output/python/qgis/_core.so python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart0.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart1.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart2.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart3.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart4.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart5.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart6.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart7.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart8.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart9.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart10.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart11.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart12.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart13.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart14.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart15.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart16.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart17.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart18.cpp.o python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart19.cpp.o -L$SRC_DIR/build/src/core   -L$SRC_DIR/build/src/gui -Wl,-rpath,$SRC_DIR/build/src/core:$SRC_DIR/build/src/gui:$SRC_DIR/build/output/lib:  $PREFIX/lib/libpython3.10.so  output/lib/libqgis_core.so.3.28.3  $PREFIX/lib/libQt5Xml.so.5.15.8  $PREFIX/lib/libQt5Svg.so.5.15.8  $PREFIX/lib/libQt5Sql.so.5.15.8  $PREFIX/lib/libQt5Concurrent.so.5.15.8  $PREFIX/lib/libQt5WebKitWidgets.so.5.212.0  $PREFIX/lib/libQt5WebKit.so.5.212.0  $PREFIX/lib/libQt5Network.so.5.15.8  $PREFIX/lib/libqca-qt5.so  $PREFIX/lib/libqt5keychain.so  $PREFIX/lib/libproj.so  $PREFIX/lib/libgeos_c.so  $PREFIX/lib/libgdal.so  $PREFIX/lib/libspatialindex.so  $PREFIX/lib/libexpat.so  $PREFIX/lib/libsqlite3.so  $PREFIX/lib/libzip.so  $PREFIX/lib/libprotobuf-lite.so  $PREFIX/lib/libz.so  $PREFIX/lib/libexiv2.so  $PREFIX/lib/libQt5PrintSupport.so.5.15.8  $PREFIX/lib/libQt5Widgets.so.5.15.8  $PREFIX/lib/libQt5Gui.so.5.15.8  $PREFIX/lib/libspatialite.so  $PREFIX/lib/libzstd.so  -lpdalcpp  $PREFIX/lib/libpdal_util.so  $PREFIX/lib/libQt5SerialPort.so.5.15.8  $PREFIX/lib/libQt5Positioning.so.5.15.8  $PREFIX/lib/libQt5Core.so.5.15.8 && :
python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart19.cpp.o: in function `meth_QgsAttributeTableConfig_setColumnWidth':
sip_corepart19.cpp:(.text+0xfbda4): relocation truncated to fit: R_PPC64_REL24 against symbol `QByteArray::~QByteArray()' defined in .text._ZN10QByteArrayD2Ev[_ZN10QByteArrayD5Ev] section in python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart0.cpp.o
python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart19.cpp.o: in function `meth_QgsAttributeTableConfig_setColumnHidden':
sip_corepart19.cpp:(.text+0xfc014): relocation truncated to fit: R_PPC64_REL24 against symbol `QByteArray::~QByteArray()' defined in .text._ZN10QByteArrayD2Ev[_ZN10QByteArrayD5Ev] section in python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart0.cpp.o
python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart19.cpp.o: in function `meth_QgsAttributeTableConfig_columnWidth':
sip_corepart19.cpp:(.text+0xfc28c): relocation truncated to fit: R_PPC64_REL24 against symbol `QByteArray::~QByteArray()' defined in .text._ZN10QByteArrayD2Ev[_ZN10QByteArrayD5Ev] section in python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart0.cpp.o
python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart19.cpp.o: in function `meth_QgsAttributeTableConfig_columnHidden':
sip_corepart19.cpp:(.text+0xfc50c): relocation truncated to fit: R_PPC64_REL24 against symbol `QByteArray::~QByteArray()' defined in .text._ZN10QByteArrayD2Ev[_ZN10QByteArrayD5Ev] section in python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart0.cpp.o
python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart19.cpp.o: in function `meth_QgsBookmarkManager_exportToFile':
sip_corepart19.cpp:(.text+0xfc994): relocation truncated to fit: R_PPC64_REL24 against symbol `QString::~QString()' defined in .text._ZN7QStringD2Ev[_ZN7QStringD5Ev] section in python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart0.cpp.o
python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart19.cpp.o: in function `init_type_QgsBookmark':
sip_corepart19.cpp:(.text+0xfcde4): relocation truncated to fit: R_PPC64_REL24 against symbol `QString::~QString()' defined in .text._ZN7QStringD2Ev[_ZN7QStringD5Ev] section in python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart0.cpp.o
sip_corepart19.cpp:(.text+0xfcdfc): relocation truncated to fit: R_PPC64_REL24 against symbol `QString::~QString()' defined in .text._ZN7QStringD2Ev[_ZN7QStringD5Ev] section in python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart0.cpp.o
sip_corepart19.cpp:(.text+0xfce14): relocation truncated to fit: R_PPC64_REL24 against symbol `QString::~QString()' defined in .text._ZN7QStringD2Ev[_ZN7QStringD5Ev] section in python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart0.cpp.o
sip_corepart19.cpp:(.text+0xfd008): relocation truncated to fit: R_PPC64_REL24 against symbol `QString::~QString()' defined in .text._ZN7QStringD2Ev[_ZN7QStringD5Ev] section in python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart0.cpp.o
sip_corepart19.cpp:(.text+0xfd020): relocation truncated to fit: R_PPC64_REL24 against symbol `QString::~QString()' defined in .text._ZN7QStringD2Ev[_ZN7QStringD5Ev] section in python/CMakeFiles/python_module_qgis__core.dir/core/build/_core/sip_corepart0.cpp.o
sip_corepart19.cpp:(.text+0xfd038): additional relocation overflows omitted from the output
```

**Comment by jayfurmanek** [comment]
Typically for that kind of problem you want to try adding `-mcmodel=medium` to the compiler command line.

**Comment by gillins** [comment]
Thanks @jayfurmanek - I tried `-mcmodel=large` also but no luck. Perhaps Qt has to be recompiled with this also?

**Pull request closed without merging**
