### PR TITLE
Updateall

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Attempt to update all qgis stuff at once.

### CODE REVIEW

**Comment by izahn** [comment]
Needs https://github.com/conda-forge/qscintilla2-feedstock/pull/45 (I think).

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
The last commit succeeded on OSX, but failed on Linux with
```
[4939/5046] Generating core/build/_core/sip_corepart0.cpp, core/build/_core/sip_corepart1.cpp, core/build/_core/sip_corepart2.cpp, core/build/_core/sip_corepart3.cpp, core/build/_core/sip_corepart4.cpp, core/build/_core/sip_corepart5.cpp, core/build/_core/sip_corepart6.cpp, core/build/_core/sip_corepart7.cpp, core/build/_core/sip_corepart8.cpp, core/build/_core/sip_corepart9.cpp, core/build/_core/sip_corepart10.cpp, core/build/_core/sip_corepart11.cpp, core/build/_core/sip_corepart12.cpp, core/build/_core/sip_corepart13.cpp, core/build/_core/sip_corepart14.cpp, core/build/_core/sip_corepart15.cpp
FAILED: python/core/build/_core/sip_corepart0.cpp python/core/build/_core/sip_corepart1.cpp python/core/build/_core/sip_corepart2.cpp python/core/build/_core/sip_corepart3.cpp python/core/build/_core/sip_corepart4.cpp python/core/build/_core/sip_corepart5.cpp python/core/build/_core/sip_corepart6.cpp python/core/build/_core/sip_corepart7.cpp python/core/build/_core/sip_corepart8.cpp python/core/build/_core/sip_corepart9.cpp python/core/build/_core/sip_corepart10.cpp python/core/build/_core/sip_corepart11.cpp python/core/build/_core/sip_corepart12.cpp python/core/build/_core/sip_corepart13.cpp python/core/build/_core/sip_corepart14.cpp python/core/build/_core/sip_corepart15.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart0.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart1.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart2.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart3.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart4.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart5.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart6.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart7.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart8.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart9.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart10.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart11.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart12.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart13.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart14.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart15.cpp 
cd $SRC_DIR/build/python/core && $BUILD_PREFIX/bin/cmake -E echo && $PREFIX/bin/sip-build --no-protected-is-public --pep484-pyi --no-make --concatenate=16 --qmake=$PREFIX/bin/qmake --include-dir=$SRC_DIR/build/python --include-dir=$PREFIX/lib/python3.9/site-packages/PyQt5/bindings && $BUILD_PREFIX/bin/cmake -E touch $SRC_DIR/build/python/core/build/_core/sip_corepart0.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart1.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart2.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart3.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart4.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart5.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart6.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart7.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart8.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart9.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart10.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart11.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart12.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart13.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart14.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart15.cpp
```

**Comment by SrNetoChan** [comment]
Since you are trying to update all, maybe you should update qgis to 3.26?

3.24 is irrelevant since it's not even an LTR version.

**Comment by izahn** [comment]
> Since you are trying to update all, maybe you should update qgis to 3.26?
> 
> 3.24 is irrelevant since it's not even an LTR version.

Thanks, I saw 3.24 was the last update PR in https://github.com/conda-forge/qgis-feedstock/pulls and thought that was the most recent one!

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
I suspect we are hitting a problem with `sip=6.6.2`. Archlinux patched their sip build in https://github.com/archlinux/svntogit-packages/commit/484c44e7909d59953e783d0b863b6f3a1eb1eb2d , referencing "Backport qgis build fix". I'm kind of inclined to just wait for `sip=6.6.3`

**Comment by SrNetoChan** [comment]
The wait has been long, so I guess we can wait a bit longer. Thanks for all your work!

**Comment by izahn** [comment]
I tried building sip with the archlinux patches and then using that to build qgis locally. Same error. So we need to figure out what
```
Generating core/build/_core/sip_corepart0.cpp, core/build/_core/sip_corepart1.cpp, core/build/_core/sip_corepart2.cpp, core/build/_core/sip_corepart3.cpp, core/build/_core/sip_corepart4.cpp, core/build/_core/sip_corepart5.cpp, core/build/_core/sip_corepart6.cpp, core/build/_core/sip_corepart7.cpp, core/build/_core/sip_corepart8.cpp, core/build/_core/sip_corepart9.cpp, core/build/_core/sip_corepart10.cpp, core/build/_core/sip_corepart11.cpp, core/build/_core/sip_corepart12.cpp, core/build/_core/sip_corepart13.cpp, core/build/_core/sip_corepart14.cpp, core/build/_core/sip_corepart15.cpp
FAILED: python/core/build/_core/sip_corepart0.cpp python/core/build/_core/sip_corepart1.cpp python/core/build/_core/sip_corepart2.cpp python/core/build/_core/sip_corepart3.cpp python/core/build/_core/sip_corepart4.cpp python/core/build/_core/sip_corepart5.cpp python/core/build/_core/sip_corepart6.cpp python/core/build/_core/sip_corepart7.cpp python/core/build/_core/sip_corepart8.cpp python/core/build/_core/sip_corepart9.cpp python/core/build/_core/sip_corepart10.cpp python/core/build/_core/sip_corepart11.cpp python/core/build/_core/sip_corepart12.cpp python/core/build/_core/sip_corepart13.cpp python/core/build/_core/sip_corepart14.cpp python/core/build/_core/sip_corepart15.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart0.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart1.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart2.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart3.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart4.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart5.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart6.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart7.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart8.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart9.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart10.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart11.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart12.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart13.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart14.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart15.cpp 
cd $SRC_DIR/build/python/core && $BUILD_PREFIX/bin/cmake -E echo && $PREFIX/bin/sip-build --no-protected-is-public --pep484-pyi --no-make --concatenate=16 --qmake=$PREFIX/bin/qmake --include-dir=$SRC_DIR/build/python --include-dir=$PREFIX/lib/python3.9/site-packages/PyQt5/bindings && $BUILD_PREFIX/bin/cmake -E touch $SRC_DIR/build/python/core/build/_core/sip_corepart0.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart1.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart2.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart3.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart4.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart5.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart6.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart7.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart8.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart9.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart10.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart11.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart12.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart13.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart14.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart15.cpp
```
means and how to fix it. Any thoughts @conda-forge/qgis ?

**Comment by gillins** [comment]
So there's no actual error message? I've seen problems at this stage before when running out of disc space and/or memory (those `sip` generated files are very large). Thanks for pushing on with this BTW.

**Comment by izahn** [comment]
Right, there's no error message it just says "FAILED: ..."

I get the same error locally too, and I should have enough disk space and memory here. Maybe worth trying with `ninja -j1` to reduce resource requirements, I'll try that next.

**Comment by izahn** [comment]
Turning of parallel ninja jobs made it easier to see that there is actually an error message:

```
AttributeError: 'ScopedName' object has no attribute 'replace'
```

There is an issue referencing this error at https://github.com/qgis/QGIS/issues/49214 so we at least have a lead for figuring this out. I'm still kind of stumped though, help appreciated.

Some context for the error message is provided below.

```
[5085/5204] Generating core/build/_core/sip_corepart0.cpp, core/build/_core/sip_corepart1.cpp, core/build/_core/sip_corepart2.cpp, core/build/_core/sip_corepart3.cpp, core/build/_core/sip_corepart4.cpp, core/build/_core/sip_corepart5.cpp, core/build/_core/sip_corepart6.cpp, core/build/_core/sip_corepart7.cpp, core/build/_core/sip_corepart8.cpp, core/build/_core/sip_corepart9.cpp, core/build/_core/sip_corepart10.cpp, core/build/_core/sip_corepart11.cpp, core/build/_core/sip_corepart12.cpp, core/build/_core/sip_corepart13.cpp, core/build/_core/sip_corepart14.cpp, core/build/_core/sip_corepart15.cpp, core/build/_core/sip_corepart16.cpp, core/build/_core/sip_corepart17.cpp, core/build/_core/sip_corepart18.cpp
FAILED: python/core/build/_core/sip_corepart0.cpp python/core/build/_core/sip_corepart1.cpp python/core/build/_core/sip_corepart2.cpp python/core/build/_core/sip_corepart3.cpp python/core/build/_core/sip_corepart4.cpp python/core/build/_core/sip_corepart5.cpp python/core/build/_core/sip_corepart6.cpp python/core/build/_core/sip_corepart7.cpp python/core/build/_core/sip_corepart8.cpp python/core/build/_core/sip_corepart9.cpp python/core/build/_core/sip_corepart10.cpp python/core/build/_core/sip_corepart11.cpp python/core/build/_core/sip_corepart12.cpp python/core/build/_core/sip_corepart13.cpp python/core/build/_core/sip_corepart14.cpp python/core/build/_core/sip_corepart15.cpp python/core/build/_core/sip_corepart16.cpp python/core/build/_core/sip_corepart17.cpp python/core/build/_core/sip_corepart18.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart0.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart1.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart2.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart3.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart4.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart5.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart6.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart7.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart8.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart9.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart10.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart11.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart12.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart13.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart14.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart15.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart16.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart17.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart18.cpp 
cd $SRC_DIR/build/python/core && $BUILD_PREFIX/bin/cmake -E echo && $PREFIX/bin/sip-build --no-protected-is-public --pep484-pyi --no-make --concatenate=19 --qmake=$PREFIX/bin/qmake --include-dir=$SRC_DIR/build/python --include-dir=$PREFIX/lib/python3.10/site-packages/PyQt5/bindings && $BUILD_PREFIX/bin/cmake -E touch $SRC_DIR/build/python/core/build/_core/sip_corepart0.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart1.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart2.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart3.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart4.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart5.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart6.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart7.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart8.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart9.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart10.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart11.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart12.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart13.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart14.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart15.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart16.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart17.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart18.cpp

Querying qmake about your Qt installation...
These bindings will be built: core.
Generating the core bindings...
sip-build: An internal error occurred...
Traceback (most recent call last):
  File "$PREFIX/bin/sip-build", line 11, in <module>
    sys.exit(main())
  File "$PREFIX/lib/python3.10/site-packages/sipbuild/tools/build.py", line 37, in main
    handle_exception(e)
  File "$PREFIX/lib/python3.10/site-packages/sipbuild/exceptions.py", line 81, in handle_exception
    raise e
  File "$PREFIX/lib/python3.10/site-packages/sipbuild/tools/build.py", line 34, in main
    project.build()
  File "$PREFIX/lib/python3.10/site-packages/sipbuild/project.py", line 244, in build
    self.builder.build()
  File "$PREFIX/lib/python3.10/site-packages/sipbuild/builder.py", line 48, in build
    self._generate_bindings()
  File "$PREFIX/lib/python3.10/site-packages/sipbuild/builder.py", line 277, in _generate_bindings
    buildable = bindings.generate()
  File "$PREFIX/lib/python3.10/site-packages/sipbuild/bindings.py", line 166, in generate
    spec, sip_files = parse(self.sip_file, SIP_VERSION, encoding,
  File "$PREFIX/lib/python3.10/site-packages/sipbuild/generator/parser/parser.py", line 35, in parse
    protected_is_public, include_dirs, strict).parse(sip_file)

```

**Comment by izahn** [comment]
I applied the sip patches from https://github.com/archlinux/svntogit-packages/blob/packages/sip/trunk/PKGBUILD and tried building `qgis` with that. It seems to fix the ` 'ScopedName' object has no attribute 'replace'` error, but we still get 

```
[5084/5204] Running utility command for pyutils
[5085/5204] Generating core/build/_core/sip_corepart0.cpp, core/build/_core/sip_corepart1.cpp, core/build/_core/sip_corepart2.cpp, core/build/_core/sip_corepart3.cpp, core/build/_core/sip_corepart4.cpp, core/build/_core/sip_corepart5.cpp, core/build/_core/sip_corepart6.cpp, core/build/_core/sip_corepart7.cpp, core/build/_core/sip_corepart8.cpp, core/build/_core/sip_corepart9.cpp, core/build/_core/sip_corepart10.cpp, core/build/_core/sip_corepart11.cpp, core/build/_core/sip_corepart12.cpp, core/build/_core/sip_corepart13.cpp, core/build/_core/sip_corepart14.cpp, core/build/_core/sip_corepart15.cpp, core/build/_core/sip_corepart16.cpp, core/build/_core/sip_corepart17.cpp, core/build/_core/sip_corepart18.cpp
FAILED: python/core/build/_core/sip_corepart0.cpp python/core/build/_core/sip_corepart1.cpp python/core/build/_core/sip_corepart2.cpp python/core/build/_core/sip_corepart3.cpp python/core/build/_core/sip_corepart4.cpp python/core/build/_core/sip_corepart5.cpp python/core/build/_core/sip_corepart6.cpp python/core/build/_core/sip_corepart7.cpp python/core/build/_core/sip_corepart8.cpp python/core/build/_core/sip_corepart9.cpp python/core/build/_core/sip_corepart10.cpp python/core/build/_core/sip_corepart11.cpp python/core/build/_core/sip_corepart12.cpp python/core/build/_core/sip_corepart13.cpp python/core/build/_core/sip_corepart14.cpp python/core/build/_core/sip_corepart15.cpp python/core/build/_core/sip_corepart16.cpp python/core/build/_core/sip_corepart17.cpp python/core/build/_core/sip_corepart18.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart0.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart1.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart2.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart3.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart4.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart5.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart6.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart7.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart8.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart9.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart10.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart11.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart12.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart13.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart14.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart15.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart16.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart17.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart18.cpp 
cd $SRC_DIR/build/python/core && $BUILD_PREFIX/bin/cmake -E echo && $PREFIX/bin/sip-build --no-protected-is-public --pep484-pyi --no-make --concatenate=19 --qmake=$PREFIX/bin/qmake --include-dir=$SRC_DIR/build/python --include-dir=$PREFIX/lib/python3.9/site-packages/PyQt5/bindings && $BUILD_PREFIX/bin/cmake -E touch $SRC_DIR/build/python/core/build/_core/sip_corepart0.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart1.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart2.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart3.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart4.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart5.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart6.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart7.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart8.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart9.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart10.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart11.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart12.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart13.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart14.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart15.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart16.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart17.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart18.cpp

Querying qmake about your Qt installation...
These bindings will be built: core.
Generating the core bindings...
Generating the _core .pyi file...
Generating the .pro file for the _core module...
Generating the top-level .pro file...
Generating the Makefiles...
sip-build: '$PREFIX/bin/qmake -recursive QGIS.pro' failed returning 3
ninja: build stopped: subcommand failed.
```

Sorry to reach out directly @nyalldawson but do you have any idea what could be going wrong here? The full build log can be found at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=549681&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412

**Comment by nyalldawson** [comment]
@izahn 

Hmmm... well that error doesn't give any useful clues at all! :upside_down_face: 

Which QGIS version were you building when you hit this one?

**Comment by izahn** [comment]
Yeah not much to go on, thanks for taking a look! This is `qgis 3.26.1`, build script at https://github.com/izahn/qgis-feedstock/blob/updateall/recipe/build.sh .

**Comment by danschef** [comment]
I don´t know much about building qgis but at least on Linux and OSX, I still see `AttributeError: 'ScopedName' object has no attribute 'replace'`.

On Windows, it is this one:

```
Traceback (most recent call last):
  File "C:\bld\qgis_1660237280463\work\cmake\FindSIP.py", line 34, in <module>
    import sipbuild
ModuleNotFoundError: No module named 'sipbuild'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bld\qgis_1660237280463\work\cmake\FindSIP.py", line 44, in <module>
    import sipconfig
ModuleNotFoundError: No module named 'sipconfig'
CMake Error at cmake/FindSIP.cmake:58 (MESSAGE):
  Could not find SIP
Call Stack (most recent call first):
  CMakeLists.txt:979 (find_package)
```

**Comment by izahn** [comment]
> I don´t know much about building qgis but at least on Linux and OSX, I still see `AttributeError: 'ScopedName' object has no attribute 'replace'`.

That error is caused by a bub in `sip` which I have patched and used to build the python 3.9 version here. You can see that this does fix it by examining the `linux linux_64_python3.9.____cpython` build log at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=549681&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412

> On Windows, it is this one:

I haven't spent much time on that yet but I'm not as concerned about it, at least the error tells us what the problem is.

**Comment by izahn** [comment]
> Which QGIS version were you building when you hit this one?

I get this with both `3.26.1` and `3.22.9`, it must have to do with our build environment.

**Comment by danschef** [comment]
> used to build the python 3.9 version here

Ok, I missed that.
Not exactly the same but seems quite similar: https://github.com/Homebrew/discussions/discussions/2050
Maybe we know more when applying the patch also to an OSX build.

> at least the error tells us what the problem is

That is right but `import sipbuild` should work on Windows if sip is defined in the host requirements (which it is). At least it works when I create an environment on Windows with `mamba create -n siptest python=3.10 sip`.

**Comment by izahn** [comment]
Well folks I've taken this as far as I can for the moment. My plan is just to wait for a while and hope that a future update to the dependency causing this problem will magically resolve it here.

If anyone else is inspired to give it a go that would be great. Basically the `qt`-induced log jam that has kept this package on `3.18` for that past 18 months has been broken, `qt-main=5.15`-compatible versions of all the dependencies are now available. `qgis` can finally be updated, if we can just get it to build @conda-forge/qgis

**Comment by izahn** [comment]
Just tried building with the dev version of `sip 6.7.0`, still get the same thing:
```
[4653/6539] Generating core/build/_core/sip_corepart0.cpp, core/build/_core/sip_corepart1.cpp, core/build/_core/sip_corepart2.cpp, core/build/_core/sip_corepart3.cpp, core/build/_core/sip_corepart4.cpp, core/build/_core/sip_corepart5.cpp, core/build/_core/sip_corepart6.cpp, core/build/_core/sip_corepart7.cpp, core/build/_core/sip_corepart8.cpp, core/build/_core/sip_corepart9.cpp, core/build/_core/sip_corepart10.cpp, core/build/_core/sip_corepart11.cpp, core/build/_core/sip_corepart12.cpp, core/build/_core/sip_corepart13.cpp, core/build/_core/sip_corepart14.cpp, core/build/_core/sip_corepart15.cpp, core/build/_core/sip_corepart16.cpp, core/build/_core/sip_corepart17.cpp, core/build/_core/sip_corepart18.cpp
FAILED: python/core/build/_core/sip_corepart0.cpp python/core/build/_core/sip_corepart1.cpp python/core/build/_core/sip_corepart2.cpp python/core/build/_core/sip_corepart3.cpp python/core/build/_core/sip_corepart4.cpp python/core/build/_core/sip_corepart5.cpp python/core/build/_core/sip_corepart6.cpp python/core/build/_core/sip_corepart7.cpp python/core/build/_core/sip_corepart8.cpp python/core/build/_core/sip_corepart9.cpp python/core/build/_core/sip_corepart10.cpp python/core/build/_core/sip_corepart11.cpp python/core/build/_core/sip_corepart12.cpp python/core/build/_core/sip_corepart13.cpp python/core/build/_core/sip_corepart14.cpp python/core/build/_core/sip_corepart15.cpp python/core/build/_core/sip_corepart16.cpp python/core/build/_core/sip_corepart17.cpp python/core/build/_core/sip_corepart18.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart0.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart1.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart2.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart3.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart4.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart5.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart6.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart7.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart8.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart9.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart10.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart11.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart12.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart13.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart14.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart15.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart16.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart17.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart18.cpp 
cd $SRC_DIR/build/python/core && $BUILD_PREFIX/bin/cmake -E echo && $PREFIX/bin/sip-build --no-protected-is-public --pep484-pyi --no-make --concatenate=19 --qmake=$PREFIX/bin/qmake --include-dir=$SRC_DIR/build/python --include-dir=$PREFIX/lib/python3.9/site-packages/PyQt5/bindings && $BUILD_PREFIX/bin/cmake -E touch $SRC_DIR/build/python/core/build/_core/sip_corepart0.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart1.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart2.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart3.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart4.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart5.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart6.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart7.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart8.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart9.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart10.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart11.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart12.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart13.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart14.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart15.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart16.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart17.cpp $SRC_DIR/build/python/core/build/_core/sip_corepart18.cpp
```
Full log at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=566263&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412

Really strange.

**Pull request closed without merging**
