### PR TITLE
Bumps version to 3.8.2

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
I am messing around with the .ci_support yaml files, which I now read that I am not supposed to. Nevertheless, I wanted to test if moving the version back to their original values would build QGIS.

**Comment by SrNetoChan** [comment]
If we are facing conflicts, what should we do to force the recipe to use old versions of the dependencies? instead of changing the ci_suport files? add version numbers to the recipe?

**Comment by SrNetoChan** [comment]
So, ignoring the changes that conda-smithy made in terms of dependencies versions, The build runs (check linux linux_python3.6). @ocefpaf @gillins should I just revert those changes for all dependencies, allow the build to success and merge it, so we can have 3.8.2 packages, and then create a PR with a re-rendered version for someone to tackle the conflicts? Unfortunately, I don't know how.

**Comment by ocefpaf** [comment]
Probably needs https://github.com/conda-forge/gdal-feedstock/pull/333

**Comment by SrNetoChan** [comment]
So, @ocefpaf instead of changing the .ci_support files to pin the versions of some packages, should I change the conda_build_config.yaml? Will the smithy honor that and change the .ci_support files accordingly?

**Comment by ocefpaf** [comment]
@gillins any idea of what may be wrong here with Windows?

**Comment by gillins** [comment]
Error comes from running `pyrcc5.bat`. It has the `pyqt` build path to Python hardcoded in it... Is this a known problem?

I think on older `pyqt` we called an `.exe` directly (I remember we had a patch)

```
@C:\bld\pyqt_1564799178857\_h_env\python.exe -m PyQt5.pyrcc_main %1 %2 %3 %4 %5 %6 %7 %8 %9
```

**Comment by ocefpaf** [comment]
> I think on older `pyqt` we called an `.exe` directly (I remember we had a patch)

Patch here for `qgis` or in `pyqt`? I can try to refresh it.

**Comment by gillins** [comment]
There is no `.exe` with the new `qt`... I think we have to fix the `pyqt` recipe so the `.bat` file doesn't have the path in it, but not sure how to do this.

**Comment by ocefpaf** [comment]
> There is no `.exe` with the new `qt`... I think we have to fix the `pyqt` recipe so the `.bat` file doesn't have the path in it, but not sure how to do this.

Looking into it...

**Comment by ocefpaf** [comment]
Closing and re-opening to toggle the CIs.

**Comment by gillins** [comment]
OK my bad - latest build of `pyqt` still has the `pyqt` build environment embedded in it. Anyone have an idea why conda-build isn't detecting this and replacing like it does on Unix??

```
$ cat Library/bin/pyrcc5.bat 
@ C:\bld\pyqt_1567694244485\_h_env\python.exe -m PyQt5.pyrcc_main %1 %2 %3 %4 %5 %6 %7 %8 %9
```

**Pull request merged**
