### PR TITLE
Changed PROJ_LIB path to share\proj 

### LINKED ISSUE #145: layer CRS not correctly detected
Issue:

For some raster and vector layers conda QGIS is not able to detect the CRS.

E.g. C:/miniconda/envs/qgis/Library/resources/data/world_map.gpkg|layername=countries 

image

In standard OSGeo4W QGIS the CRS is correctly detected.

Also in the conda console it seams to work:

```
(qgis) C:\Users\janzandr>python
Python 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 00:43:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from qgis.core import QgsVectorLayer
>>> v = QgsVectorLayer('C:/miniconda/envs/qgis/Library/resources/data/world_map.gpkg|layername=countries')
>>> v.crs()
<QgsCoordinateReferenceSystem: EPSG:4326>
```
 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
blas                      1.0                         mkl
boost-cpp                 1.72.0               h89d28cc_2    conda-forge
brotlipy                  0.7.0           py38h1e8a9f7_1000    conda-forge
bzip2                     1.0.8                he774522_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cairo                     1.16.0            h8a5e50b_1003    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.1           py38hba49e27_0    conda-forge
cfitsio                   3.470                hbbe6aef_6    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
coverage                  5.2.1            py38h1e8a9f7_0    conda-forge
cryptography              3.1              py38hba49e27_0    conda-forge
curl                      7.71.1               h4b64cdc_5    conda-forge
exiv2                     0.27.1               hfa2c1cf_0    conda-forge
expat                     2.2.9                h33f27b4_2    conda-forge
freetype                  2.10.2               hd328e21_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
future                    0.18.2           py38h32f6830_1    conda-forge
gdal                      3.1.1            py38h3ba59e7_0    conda-forge
geos                      3.8.1                he025d50_0    conda-forge
geotiff                   1.6.0                hcadc5cd_0    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.65.0               he4de6d7_0    conda-forge
gsl                       2.6                  h86b8168_0    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.6          nompi_he0bbb20_101    conda-forge
httplib2                  0.18.1             pyh9f0ad1d_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
intel-openmp              2020.1                      216
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.16.0                     py_0    conda-forge
jpeg                      9d                   he774522_0    conda-forge
kealib                    1.4.13               h3b59ab9_1    conda-forge
krb5                      1.17.1               hc04afaa_3    conda-forge
libblas                   3.8.0                    16_mkl    conda-forge
libcblas                  3.8.0                    16_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libcurl                   7.71.1               h4b64cdc_5    conda-forge
libffi                    3.2.1             ha925a31_1007    conda-forge
libgdal                   3.1.1                hbc6966c_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h7e985d0_1011    conda-forge
liblapack                 3.8.0                    16_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h256d12c_105    conda-forge
libpng                    1.6.37               ha81a0f5_2    conda-forge
libpq                     12.3                 hd9aa61d_0    conda-forge
libprotobuf               3.11.4               h1a1b453_0    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             4.3.0a            h51df0ed_1038    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp-base              1.1.0                hfa6e2cd_3    conda-forge
libxml2                   2.9.10               h1006b36_2    conda-forge
libzip                    1.5.1             h8f0db0c_1005    conda-forge
lz4-c                     1.9.2                h62dcd97_2    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.1            py38h9de7a3e_1    conda-forge
mkl                       2020.1                      216
mkl-service               2.3.0            py38hb782905_0
mock                      4.0.2            py38h32f6830_0    conda-forge
msys2-conda-epoch         20160418                      1
nose2                     0.9.2                      py_0    conda-forge
numpy                     1.19.1           py38h72c728b_0    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1g               he774522_1    conda-forge
owslib                    0.20.0                     py_0    conda-forge
pcre                      8.44                 h6538335_0    conda-forge
pip                       20.2.3                     py_0    conda-forge
pixman                    0.38.0            hfa6e2cd_1003    conda-forge
plotly                    4.9.0              pyh9f0ad1d_0    conda-forge
poppler                   0.89.0               h5d62644_1    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.3                 he14cc48_0    conda-forge
proj                      7.0.0                haa36216_5    conda-forge
psycopg2                  2.8.6            py38hba49e27_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyproj                    2.6.1.post1      py38h1dd9442_0    conda-forge
pyqt                      5.12.3           py38h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.5           h60c2a47_7_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py38h9de7a3e_0    conda-forge
qca                       2.2.1                hd7ce7fb_3    conda-forge
qgis                      3.14.1           py38h21d4842_0    conda-forge
qjson                     0.9.0             hd7ce7fb_1006    conda-forge
qscintilla2               2.11.2           py38h19e3e1c_2    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtkeychain                0.10.0               hd7ce7fb_0    conda-forge
qtlocation                5.12.5               he025d50_0    conda-forge
qwt                       6.1.5                h265ddaf_0    conda-forge
qwtpolar                  1.1.1                hd7ce7fb_7    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
scikit-learn              0.23.2           py38hf00eced_0    conda-forge
scipy                     1.5.0            py38h9439919_0
setuptools                49.6.0           py38h32f6830_0    conda-forge
sip                       4.19.20          py38h6538335_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               he774522_0    conda-forge
tbb                       2020.1               he980bc4_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tiledb                    2.0.8                h71c485d_0    conda-forge
tk                        8.6.10               he774522_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
win_inet_pton             1.1.0                    py38_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
xerces-c                  3.2.2             h6538335_1004    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zlib                      1.2.11            h62dcd97_1009    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : qgis
    active env location : C:\miniconda\envs\qgis
            shell level : 2
       user config file : C:\Users\janzandr\.condarc
 populated config files : C:\Users\janzandr\.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.2
       base environment : C:\miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\miniconda\pkgs
                          C:\Users\janzandr\.conda\pkgs
                          C:\Users\janzandr\AppData\Local\conda\conda\pkgs
       envs directories : C:\miniconda\envs
                          C:\Users\janzandr\.conda\envs
                          C:\Users\janzandr\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by jakimowb**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Changed PROJ_LIB path from `share` to `share\proj` for windows builds to fix #145

### CODE REVIEW

**Comment by gillins** [comment]
Thanks @jakimowb can you add a test for this to `test_py_qgis.py` (like this: https://github.com/conda-forge/qgis-feedstock/issues/145#issuecomment-761926371)?

@conda-forge-admin, please rerender

**Comment by jakimowb** [comment]
@gillins I added the tests to `test_py_qgis.py`. Seems they all passed the CI checks.

**Comment by gillins** [comment]
Thanks @jakimowb !

**Comment by SrNetoChan** [comment]
Great job!

**Pull request merged**
