### PR TITLE
Update LTR to 3.10.12

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please restart ci

**Comment by SrNetoChan** [comment]
@ocefpaf I have noticed that GDAL got updated even being in the local pinning file. Have I done something wrong? It seems to be working for Proj

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please restart ci

**Comment by ocefpaf** [comment]
> @ocefpaf I have noticed that GDAL got updated even being in the local pinning file. Have I done something wrong? It seems to be working for Proj

The pinning is specifying 3.0.4, right? I could not find a log that did not used that one. Can you point it to me?

**Comment by SrNetoChan** [comment]
> > @ocefpaf I have noticed that GDAL got updated even being in the local pinning file. Have I done something wrong? It seems to be working for Proj
> 
> The pinning is specifying 3.0.4, right? I could not find a log that did not used that one. Can you point it to me?

Uhmm... you are right. I thought I had seen it somewhere, but looking again it all seems to be correct.

I can't understand what is going on with the failing tests, they are mixed SO and python version.

**Comment by ocefpaf** [comment]
The macOS could be the issues that @isuruf found with the bad targeted SDKs. I'll check it tomorrow. But the Windows it seems to be SIP and pyqt again :-(

**Comment by SrNetoChan** [comment]
@ocefpaf I have started the rebuild of sip, but I am not sure I should. Then I woukd rebuild pyqt.

**Comment by ocefpaf** [comment]
> @ocefpaf I have started the rebuild of sip, but I am not sure I should.

Thanks! We need to put a test to ensure conda-build is doing the right thing there.

> Then I woukd rebuild pyqt.

I'll take a look at sip tomorrow and, if things work, I can help with pyqt. That one is usually more complex.

**Comment by SrNetoChan** [comment]
@ocefpaf do you think we can merge this for now, and then, when possible, fix windows?

**Comment by ocefpaf** [comment]
> @ocefpaf do you think we can merge this for now, and then, when possible, fix windows?

Sure. It is not worth waiting for conda-build. I'll restart as soon as we have a new pyqt/sip that works here.

**Pull request merged**
