### PR TITLE
Support for geoparquet

### PR DESCRIPTION
**Pull request by m-kuhn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@gillins we forgot to bump the build version

**Comment by gillins** [comment]
> @gillins we forgot to bump the build version

Oh no! I'll prepare a new PR.

**Comment by gillins** [comment]
Actually, @m-kuhn would we be better off just getting users to install `libgdal-arrow-parquet` themselves if they want this functionality? This change doesn't alter the way that `qgis` is built does it?
Forcing all the optional GDAL drivers to be installed with QGIS find of defeats the purpose of having them as optional drivers in the first place....

**Comment by m-kuhn** [comment]
> Actually, @m-kuhn would we be better off just getting users to install `libgdal-arrow-parquet` themselves if they want this functionality? This change doesn't alter the way that `qgis` is built does it? Forcing all the optional GDAL drivers to be installed with QGIS find of defeats the purpose of having them as optional drivers in the first place....

I think it should be easy for a user to get a QGIS installation that supports most formats. I don't know what options there are (like `--install-recommened` or `gdal-extra` package or ...).

**Comment by SrNetoChan** [comment]
I have been wanting to move my blog post about qgis with conda to qgis.org installation webpage. In it, we can list available drivers in it.

**Comment by gillins** [comment]
The original discussion about why it was an optional driver for GDAL is here: https://github.com/conda-forge/gdal-feedstock/issues/628

**Comment by SrNetoChan** [comment]
@gillins am I correct that adding this permanently can also mean that qgis build needs to wait for arrow-parquet lib to be compatible to bump gdal version when needed?

**Comment by SrNetoChan** [comment]
I mean, qgis-feedstock gets new "dependencies".

**Comment by gillins** [comment]
Sorry, my timezone isn't the best for chatting with you guys.... 
I'm tempted to take this out, as @SrNetoChan points out this is another dependency to rebuild. And the whole point of the GDAL plugin decision was ensure the user only had to install "heavy" dependencies if they actual needed them. I know qgis is already pretty heavy but those of us on slow internet (like me!) appreciate it not getting any larger if possible.
It would be a different story if having this available at build time changed how qgis was built but AFAICT this isn't the case.
An alternative suggestion would be to add a message at install time (see https://docs.conda.io/projects/conda-build/en/stable/resources/link-scripts.html) with information about useful optional packages? Would this be ok? Some [other packages](https://github.com/search?q=org%3Aconda-forge%20.messages.txt&type=code) already use this feature.

**Comment by SrNetoChan** [comment]
@gillins @m-kuhn sounds like a good compromise. We can even have a larger list of libraries and packages that are commonly installed with qgis (in osgeo4w for example).

**Comment by gillins** [comment]
Do you want to send me some wording with a list of optional packages and their uses? I can do it as part of #387.

**Comment by SrNetoChan** [comment]
Uhmm... I will have to study it.

**Comment by mtravis** [comment]
Thanks for looking into this. I'm not that clued up to how Conda packages are built but if GDAL 3.5 ships with (geo)parquet / arrow and say do recent versions of QGIS as a result of this then this just isn't another optional package is it?

Also, more and more datasets are started to be produced as geoparquet other software is able to open it so I feel like this is a bit of a blocker for QGIS users on MAC and Linux. 

Worth noting that there is also funding available to help get this fixed if needed.

**Comment by gillins** [comment]
Conda GDAL doesn't ship with parquet (see https://github.com/conda-forge/gdal-feedstock/issues/628), it's an optional plugin the user has to install if they want it (`conda install libgdal-arrow-parquet`). They felt it was too large a dependency to force on everyone who uses GDAL. 
Anyone who needs parquet will have to install the plugin manually, but this shouldn't be too hard for conda users (noting that it is rare for anyone to just need QGIS without other packages for their scripting needs)....

I kind of feel that this situation is the same for any package that uses GDAL, and maybe this conversation should move to that feedstock.

However, I would point out that if users want to install QGIS with all the bells and whistles installed without having to think too much, there are installers from qgis.org that fill that need. QGIS on conda is more for people who are comfortable with identifying installing packages they need and installing them. I would say most conda users are Python programmers too so will need a variety of packages to make their scripts run.

Which brings me to another point. Just because some users may need, for example `scipy` for their scripting, should we install that too with QGIS "just in case"? Where do you stop? @SrNetoChan is putting together a list of useful optional packages that "may work well with QGIS" for us to display on installation, hopefully this may assist the novice user.

I feel we should be taking the lead from the GDAL feedstock maintainers on this. But happy to hear what everybody thinks.

Personally have have zero data in parquet format and definitely wouldn't appreciate the extra download on my slow metered internet each time I install QGIS, but perhaps I'm in the minority here....

**Comment by mtravis** [comment]
@gillins thanks for the detailed explanation 

I believe there is a fundamental difference here in that Geoparquet is a stable data format [recognised by the OGC](https://www.ogc.org/press-release/ogc-to-form-new-geoparquet-standards-working-group-public-comment-sought-on-draft-charter/)  and therefore the need for this package is very different to that of `scipy` as it's not for scripting but for loading cloud-native data, such as the Overture data that is not being released as geoparquet.

However I do think this needs to go upstream and I think it would makes sense for the issue to be dealt at the GDAL level. I will post something there.

**Pull request merged**
