### PR TITLE
Update QGIS stable branch to 3.34.0 Release candidate

### PR DESCRIPTION
**Pull request by SrNetoChan**
Future LTR branch in February

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@h-vetinari any ideas on why we are getting failures with protobuf on osx-arm64 now? Seems to be picking up the wrong binaries...

**Comment by h-vetinari** [comment]
> @h-vetinari any ideas on why we are getting failures with protobuf on osx-arm64 now? Seems to be picking up the wrong binaries...

Rather than deleting the "wrong" protoc
https://github.com/conda-forge/qgis-feedstock/blob/100a818dd5e81807c1f42f40e215e23c597334f0/recipe/build.sh#L46-L47

you should be setting `-DProtobuf_PROTOC_EXECUTABLE=$BUILD_PREFIX/bin/protoc`

**Comment by h-vetinari** [comment]
If you still run into troubles even so, you might need to do something like https://github.com/conda-forge/opencv-feedstock/commit/bbe46049a19e30c96cadbdf07affcaf0b8c6230d, c.f. also https://github.com/protocolbuffers/protobuf/issues/14576

**Comment by gillins** [comment]
Done in #380

**Comment by gillins** [comment]
Thanks for the tips @h-vetinari ! Got it running in the end.

**Pull request closed without merging**
