### PR TITLE
Update LTR to 3.10.7

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@ocefpaf do we still need to move back to C: after rerender?

**Comment by ocefpaf** [comment]
> @ocefpaf do we still need to move back to C: after rerender?

Sadly yes. But we have a cmake failure here.

**Comment by SrNetoChan** [comment]
Maybe something related with the new 2017 compiler?

**Comment by ocefpaf** [comment]
> Maybe something related with the new 2017 compiler?

Could be but I'm not certain. @gillins and @isuruf do you have am insight for us here?

**Comment by isuruf** [comment]
Please use a fork in the future.

**Comment by SrNetoChan** [comment]
@isuruf Sorry about not using a fork. I though I did it, but it was all done using github interface.

**Comment by SrNetoChan** [comment]
@ocefpaf @isuruf  do you want me to move this to a fork and close these two branches?

**Comment by ocefpaf** [comment]
> @ocefpaf @isuruf do you want me to move this to a fork and close these two branches?

If this was passing I would say no, but b/c it is still failing it is probably better. Thanks!

**Comment by SrNetoChan** [comment]
@ocefpaf @isuruf moved this to a fork based PR in #130

**Pull request closed without merging**
