### PR TITLE
Make SIP succeed by providing g++ via links

### PR DESCRIPTION
**Pull request by gillins**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

A bit of a longshot to see if this fixes the Linux building issue.

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
Interesting. With `--verbose` being passed to `sip-build` I get the following error. I think we had the same thing years ago?
```
$PREFIX/bin/qmake -recursive QGIS.pro
Project ERROR: Cannot run compiler 'g++'. Output:
===================
===================
Maybe you forgot to setup the environment?
sip-build: '$PREFIX/bin/qmake -recursive QGIS.pro' failed returning 3
```

**Comment by gillins** [comment]
Approach stolen from `pyqt`. I've also removed some patches that appeared to be no longer needed.

**Comment by SrNetoChan** [comment]
Assuming everything builds, tomorrow I will try to merge this into the LTR branch.

**Pull request merged**
