### PR TITLE
Fix Library\Library in PATH (Issue #56)

### PR DESCRIPTION
**Pull request by lpinner**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)

Resolves  conda-forge/qgis-feedstock#56

### CODE REVIEW

**Comment by lpinner** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@ocefpaf I see the pinning for `qt` has already moved to 5.9. Has everything apart from `qgis` already moved? If so, I guess we will have to wait until `qgis` has moved to `qt` 5.9 before merging this...

**Comment by ocefpaf** [comment]
> @ocefpaf I see the pinning for `qt` has already moved to 5.9. Has everything apart from `qgis` already moved?

Not everything, we are still missing `qgis` and `freecad`. In theory, if the bot follow the graph correctly, all `qgis` dependencies should be using `qt 5.9` now.

BTW, you can follow the `qt` migration and others in our status page: https://conda-forge.org/status.

**Comment by ocefpaf** [comment]
@lpinner it was easier to add this manually in https://github.com/conda-forge/qgis-feedstock/pull/48/commits/21fcee084d16736beb3162f3886bbd3208b65580 than to rebase this PR. Thanks for the fix!

**Pull request closed without merging**
