### PR TITLE
Update ltr 3.10.7

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@ocefpaf isn't it strange that OSX with Python 3.6 and 3.8 failed, while 3.7 passed!? I the official releases of QGIS, the LTR branch has PROJ and GDAL versions pinned. Should I try the same?

Thanks!

**Comment by SrNetoChan** [comment]
> @ocefpaf isn't it strange that OSX with Python 3.6 and 3.8 failed, while 3.7 passed!? I the official releases of QGIS, the LTR branch has PROJ and GDAL versions pinned. Should I try the same?
> 
> Thanks!

ok re-running the tests fixed it.

**Comment by ocefpaf** [comment]
> > @ocefpaf isn't it strange that OSX with Python 3.6 and 3.8 failed, while 3.7 passed!? I the official releases of QGIS, the LTR branch has PROJ and GDAL versions pinned. Should I try the same?

Sorry. I'm late here. Looks like those are passing now, except for Windows :-(

Do you want to merge to get Linux and macOS in? Looks like windows depend on things that are beyond our control at the moment.

**Comment by SrNetoChan** [comment]
Builts for Linux and Mac are already on the  conda-forge channel, we can keep this open until windows build is ok

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please restart ci

**Comment by SrNetoChan** [comment]
@ocefpaf I am merging this one too. Osx is failing, but we already have working builds for osx

**Comment by ocefpaf** [comment]
> @ocefpaf I am merging this one too. Osx is failing, but we already have working builds for osx

:+1:

**Pull request merged**
