### PR TITLE
Pin proj4

### PR DESCRIPTION
**Pull request by ocefpaf**
@ceholden do not merge this one yet! We need https://github.com/conda-forge/libspatialite-feedstock/pull/12 and https://github.com/conda-forge/gdal-feedstock/pull/115 first.

I am cancelling the CIs and re-starting them once `libspatialite` and `gdal` made into the channel.

### CODE REVIEW

**Comment by ceholden** [comment]
@ocefpaf this replaces #3 as well then, right? I haven't had the time to keep up in the loop on this stuff unfortunately but I'll try to catch up tonight or tomorrow.

Thanks!

**Comment by ocefpaf** [comment]
> @ocefpaf this replaces #3 as well then, right?

Yep.

>  I haven't had the time to keep up in the loop on this stuff unfortunately but I'll try to catch up tonight or tomorrow.

Don't worry. In theory the pinning bot should take care of this. I am only doing this manually because there are not many feedstocks to pin for `pyproj`.

**Comment by ocefpaf** [comment]
@ceholden latest `gdal`, pinned for `proj.4`, is in the channel and I re-started the CIs here. If this passes feel free to merge. (I also pinned qt/pyqt btw.)

**Comment by ceholden** [comment]
Great! Thank you!

**Pull request merged**
