### PR TITLE
Update to 3.8.1

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
It seems that there are dependencies conflicts with moving to icu 64.2. @ocefpaf Does this mean that all the listed dependencies must be rerendered?

**Comment by ocefpaf** [comment]
> It seems that there are dependencies conflicts with moving to icu 64.2. @ocefpaf Does this mean that all the listed dependencies must be rerendered?

All we need is https://github.com/conda-forge/gdal-feedstock/pull/314

`icu` was probably one of the package we forgot to add explicitly in `gdal` a long time ago. I'm rebuild gdal `2.4.1` (done), `2.4.2`, and `3.0.1` with the old and the new `icu` so we can fix this one.

**Comment by ocefpaf** [comment]
Let's close and reopen to toggle the CIs.

**Comment by ocefpaf** [comment]
> It seems that there are dependencies conflicts with moving to icu 64.2. @ocefpaf Does this mean that all the listed dependencies must be rerendered?

@SrNetoChan I forgot that `qgis` depended on `qt`, so we need to keep this on the old `icu` for a while.

**Comment by ocefpaf** [comment]
We have green! Thanks @SrNetoChan!!

**Pull request merged**
