### PR TITLE
Update Recipe for QGIS 3.6 (stable branch)

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Bumped QGIS version to 3.6.1. Yet, I do not wish to merge this into master. I would prefer to keep this in a separate branch so people can install either the Long Term Release (currently 3.4.6) or the stable version (currently 3.6.1)

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@ocefpaf I saw your branches. Since we have LTR and master. I would say this PR should be merged in master. And we update LTR whenever there is a new patch for it.

**Comment by SrNetoChan** [comment]
It seems that libexiv2 is missing, which is required for 3.6

**Comment by gillins** [comment]
@ocefpaf @ceholden Which version should on the master branch and which on LTR? Seems we have 3.4 on master, but maybe that should be on LTR instead?

**Comment by ocefpaf** [comment]
> @ocefpaf @ceholden Which version should on the master branch and which on LTR? Seems we have 3.4 on master, but maybe that should be on LTR instead?

You are right. I'm refreshing LTR with master and then we can focus on this PR to get master to 3.6.

**Comment by ocefpaf** [comment]
All platforms are failing with:

```
EXIV2_INCLUDE_DIR=EXIV2_INCLUDE_DIR-NOTFOUND
EXIV2_LIBRARY=EXIV2_LIBRARY-NOTFOUND
CMake Error at cmake/FindEXIV2.cmake:21 (MESSAGE):
  Could not find exiv2
Call Stack (most recent call first):
  src/analysis/CMakeLists.txt:209 (FIND_PACKAGE)
```

`conda-forge` does not provide `exiv2` and will need to add that to satisfy this new dependency.

**Comment by SrNetoChan** [comment]
Is there any reason for OSX not being tested on this branch?

**Comment by SrNetoChan** [comment]
It seems to have stoped being tested (and probably built) with #21fcee0

**Comment by gillins** [comment]
We were having trouble with `qca` on the LTR branch (see https://github.com/conda-forge/qgis-feedstock/pull/60#issuecomment-494489893). You can try re-enabling it on this branch and see if it works...

Weird issue with Windows - seems a `qt` version problem. Do you know what the minimum version of `qt` is for `qgis` 3.6?

**Comment by SrNetoChan** [comment]
@guillins the README docs still mentions 5.9.0, and the one packaged by QGIS project for linux uses 5.9.5.

**Comment by SrNetoChan** [comment]
OSGeo4W uses 5.11.2 for QGIS 3.4, should be using the same or higher for Windows.

**Comment by ocefpaf** [comment]
> OSGeo4W uses 5.11.2 for QGIS 3.4, should be using the same or higher for Windows.

I was postponing building a new qt but I guess I have to do it now :smile: 

I'll ping back here if I can get a successful build.

**Comment by gillins** [comment]
OK I've managed to add a workaround for missing non-static `QProcess::startDetached` in `qt` 5.9. It won't be quite the same behaviour as the original, but hopefully ok. The other option is to revert https://github.com/qgis/QGIS/commit/30692fa9a3f641260dff4c6039155009e1c08981#diff-f7fb6fe688ad2ca6a37a290a4b019a64. Not sure what is best...

This seems to be the only part that needed a newer `qt` so hopefully we can continue with 5.9 for now.

**Pull request merged**
