### PR TITLE
include pdal

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
We probably need this:

https://github.com/conda-forge/pdal-feedstock/pull/123

Trying to install pdal in the same environment as qgis 3.18.0 forces it to downgrade gdal, geos and qgis (to 3.16.3)

**Comment by SrNetoChan** [comment]
@ocefpaf @gillins seems that, after pdal have bumped GEOS version the builds are now passing, can you confirm that the pdal inclusion was done correctly? I never know where to put dependencies.

**Comment by gillins** [comment]
@SrNetoChan I can't see where you've added `pdal` as a dependency on this one... Maybe I'm missing something? I'm not sure if the changes got clobbered in the force push?

Also - is there any doco about how to compile `qgis` against `pdal`?

**Comment by SrNetoChan** [comment]
@gillins I add it to the host and run lists, in the recipe.

On linux, I didn't seem to need compiling QGIS against PDAL, I just needed to have pdal installed in the system. Never the less, some folks suggested to also use the WITH_PDAL and WITH_EPT options, something I didn't try in here, yet.

**Comment by SrNetoChan** [comment]
Uhmm... Wait, something is wrong. My push removed PDAL... False alarm, this is doing nothing. Sorry for the noise...

**Comment by SrNetoChan** [comment]
Ok, back to stage 1.
pdal libgdal is still at 3.1.4, and QGIS is on 3.2.1, So I guess I need to bump the gdal version for pdal.

**Comment by gillins** [comment]
I think you will also need to pass `WITH_PDAL=TRUE` to `cmake` (https://github.com/qgis/QGIS/blob/7af87414a14a11a02ef85ed20fdf52fe36d200f0/CMakeLists.txt#L256) - seems the default is `FALSE` here...

Yep let's wait for `pdal` to catch up

**Comment by SrNetoChan** [comment]
> I think you will also need to pass `WITH_PDAL=TRUE` to `cmake` (https://github.com/qgis/QGIS/blob/7af87414a14a11a02ef85ed20fdf52fe36d200f0/CMakeLists.txt#L256) - seems the default is `FALSE` here...
> 
> Yep let's wait for `pdal` to catch up

@gillins compiling QGIS on Linux, I didn't need to use WITH_PDAL = TRUE or EPT = TRUE, I was able to use pdal from the system. WITH_PDAL seems to be used if I want to build PDAL? I am unsure, really. I will ask.

**Comment by SrNetoChan** [comment]
WITH_EPT seems to be TRUE by default, should I keep it?

**Comment by gillins** [comment]
> WITH_EPT seems to be TRUE by default, should I keep it?

Probably doesn't matter in that case. What does WITH_EPT do anyway?

**Comment by SrNetoChan** [comment]
> Probably doesn't matter in that case. What does WITH_EPT do anyway?

AFAIK to enable entwine, which is used to view point clouds.

**Comment by gillins** [comment]
Ah ok. Do we need to add `entwine` as a dependency also for this?

**Comment by SrNetoChan** [comment]
Ok, I got confirmation that we do need with_pdal=true. So, all we need now is wait for pdal to be updated.

**Comment by SrNetoChan** [comment]
> Ah ok. Do we need to add `entwine` as a dependency also for this?

@gillins we probably do, but since it hasn't complaint yet, I will only add it once I have figure out PDAL.

AFAIK entwine won't fail if not present in the system, but I am not sure what is it needed for. Besides, I think entwine is waiting for PDAL migration too.

https://conda-forge.org/status/#gdal32

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please restart ci

**Comment by SrNetoChan** [comment]
Seems that something else in PDAL (other than GDAL) is conflicting, I wonder what could it be.

I have confirmed the versions on the common dependencies in the recipes. Can the problem be farther behind? Like the dependencies of PDAL dependencies?

To find out what, I will trying to install the latest PDAL on a clean environment, and compare with QGIS environment. Is this a good plan or there are more clever ways of finding the problem?

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
> Is this a good plan or there are more clever ways of finding the problem?

Sounds reasonable to me, but @ocefpaf is the expert at working things out - I never have much luck with this type of thing.

**Comment by SrNetoChan** [comment]
Ah! step by step, we are getting there. Seems that there are no more conflicts, but windows seems to be failing.

**Comment by gillins** [comment]
Problem is on Windows that both `winsock.h` and `winsock2.h` are included which appears to cause problems see https://stackoverflow.com/questions/9153911/is-there-a-difference-between-winsock-h-and-winsock2-h)... I'll keep looking into it.

**Comment by SrNetoChan** [comment]
How about patch any inclusion of version 1 and replace it for version 2. Supposedly, version 2 is backwards compatible, and, if we are worried with 32 bit computers (not sure if that is the real issue), QGIS upstream is dropping support to 32bit on windows too.

**Comment by gillins** [comment]
I'm having a bit of trouble working which are the problem files... I'll try and look into this more next week. If you want to skip Windows for now that is fine. 

Just trying to work out why QGIS isn't finding conda's `laz-perf`, might try and get that going now.

**Comment by SrNetoChan** [comment]
@gillins one linux is failing now. If you don't mind, I will create a new pr without your patches, merge it for linux and mac, and we can keep working on fixing windows later.

**Comment by gillins** [comment]
That failure was a timeout downloading the qgis source, probably restarting will fix it. 

I ended up removing my patch. I'll look into this more when i have time so feel free to skip Windows for now. 

I did manage to link in conda's laz-perf instead of the bundled one so should be a bit neater.

**Comment by SrNetoChan** [comment]
Yes, I am going to merge it as is. Thanks for all your work.

**Pull request merged**
