### PR TITLE
add pyqtwebkit and tidy cdt usage

### LINKED ISSUE #68: Missing PyQt5 and Webkit dependencies
Issue:

When opening QGIS 3.4.8 LTR from conda installation, several plugins complained about missing dependencies, one of the plugins asks the user to install pythos3-pyqt5.qtwebkit

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /home/aneto/miniconda3/envs/qgis_ltr:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py37_1003    conda-forge
atk                       2.25.90           hb9dd440_1002    conda-forge
attrs                     19.1.0                     py_0    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.3           py37h8022711_0    conda-forge
cfitsio                   3.430             h0bd2449_1002    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
coverage                  4.5.3            py37h14c3975_0    conda-forge
cryptography              2.6.1            py37h72c5cf5_0    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
future                    0.17.1                py37_1000    conda-forge
gdal                      2.4.1            py37hf242f0b_3    conda-forge
gdk-pixbuf                2.36.12           h49783d7_1002    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
geotiff                   1.5.1                h560c3f3_2    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            hf63aee3_1001    conda-forge
gobject-introspection     1.58.2          py37h2da5eee_1000    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gsl                       2.4               h294904e_1006    conda-forge
gst-plugins-base          1.14.4            hdf3bae2_1001    conda-forge
gstreamer                 1.14.4            h66beb1c_1001    conda-forge
gtk2                      2.24.31           hb68c50a_1001    conda-forge
harfbuzz                  2.4.0                h37c48d4_0    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
httplib2                  0.12.3                   py37_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
jsonschema                3.0.1                    py37_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kealib                    1.4.10            h1978553_1003    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1
libgdal                   2.4.1                h02bbc0b_3    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
liblapack                 3.8.0               10_openblas    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.3                 h4e4e079_0    conda-forge
libspatialindex           1.9.0                he1b5a44_1    conda-forge
libspatialite             4.3.0a            h4c5cd43_1028    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_0    conda-forge
libxslt                   1.1.32            h4785a14_1002    conda-forge
libzip                    1.5.1             h2f06484_1003    conda-forge
lxml                      4.3.3            py37h7ec2d77_0    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
mock                      3.0.5                    py37_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nose2                     0.9.1                      py_0    conda-forge
numpy                     1.16.3           py37he5ce36f_0    conda-forge
openblas                  0.3.6                h6e990d7_2    conda-forge
openjpeg                  2.3.1                h58a6597_0    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
owslib                    0.17.1                     py_0    conda-forge
pango                     1.40.14           h4ea9474_1004    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       19.1                     py37_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
plotly                    3.9.0                      py_0    conda-forge
poppler                   0.67.0               h2ad7f00_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.3                 hbeee2d4_0    conda-forge
proj4                     6.1.0                he751ad9_2    conda-forge
psycopg2                  2.8.2            py37h72c5cf5_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.4.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyproj                    2.1.3            py37hc44880f_2    conda-forge
pyqt                      5.9.2            py37hcca6a23_0    conda-forge
pyrsistent                0.15.2           py37h516909a_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h5b0a415_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1              py37h14c3975_0    conda-forge
qca                       2.2.1                h279c94e_0    conda-forge
qgis                      3.4.8            py37h758d154_0    conda-forge
qjson                     0.9.0             h279c94e_1005    conda-forge
qscintilla2               2.11.1           py37hd2e5223_2    conda-forge
qt                        5.9.7                h52cfd70_2    conda-forge
qtkeychain                0.9.1             h279c94e_1001    conda-forge
qtlocation                5.9.7                he1b5a44_0    conda-forge
qtserialport              5.9.8                h279c94e_0    conda-forge
qwt                       6.1.4             h279c94e_1003    conda-forge
qwtpolar                  1.1.1                h279c94e_6    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.22.0                   py37_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sip                       4.19.8          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
tzcode                    2018g             h14c3975_1001    conda-forge
urllib3                   1.24.3                   py37_0    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xerces-c                  3.2.2             hac72e42_1001    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

    active environment : qgis_ltr
    active env location : /home/aneto/miniconda3/envs/qgis_ltr
            shell level : 1
       user config file : /home/aneto/.condarc
 populated config files : /home/aneto/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /home/aneto/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/aneto/miniconda3/pkgs
                          /home/aneto/.conda/pkgs
       envs directories : /home/aneto/miniconda3/envs
                          /home/aneto/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-48-generic ubuntu/18.04.2 glibc/
2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by gillins**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #68. Also trying to sync the use of cdt's with `qt`.

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@gillins what a fight!! Thank you for trying all this.

**Comment by gillins** [comment]
I've probably gone a bit overboard - at some stage the OSX builds broke. I'm trying to fix them by changing from building an OSX bundle (which qgis wants to do by default and is very complex) to a normal Unix install like conda expects. I wasn't a huge fan of the OSX bundle and related workarounds and suspect it might be the reason this behaviour: https://github.com/conda-forge/qgis-feedstock/issues/89#issuecomment-736218969

Trying to "undo" the OSX bundle stuff is a lot harder than I thought.... I don't know much about OSX. @jakimowb @ceholden Am I on the right track? Should this be added upstream instead?

**Comment by SrNetoChan** [comment]
@gillins seems that you got it working. As far as I know, windows builds are failing for other reasons. Should we merge for now?

**Comment by gillins** [comment]
Well that is a miracle.... I might just tidy that up a bit before merging if that's ok. Probably could do a few things to make it easier to maintain (and maybe make it suitable to upstream). 

Any news on Windows `pyqt` @ocefpaf?

**Comment by SrNetoChan** [comment]
Great job @gillins thanks. I think we will see an increase in downloads with the webkit fully functional.

**Comment by gillins** [comment]
Is it working how you expected with webket now @SrNetoChan ? I'll have a look at porting this to the LTR branch when I get a chance.

@jakimowb does the latest build (3.16.1 build 2) work on now on OSX?

**Comment by SrNetoChan** [comment]
@gillins tried just now in Linux and it works like a charm!!

I am trying to get someone testing on MacOS.

Don't waste time porting to the LTR. It's probably too much work, and 3.16.4 will become the LTR in February, so all we will need to do is force merge this recipe into the LTR branch, and move stable to 3.18.0.

Again, thanks for all your work.

**Comment by jakimowb** [comment]
Sorry @gillins, I updated my macOS 11.1 conda-forge QGIS to py38h03ef37c_2 but still can't start QGIS.
However, I can't do so with the Qt Designer as well, so maybe this is something more general and not just a QGIS problem?

This is how it looks in the macOS "Force Quit" window: 
`qgis` was started from the conda shell, `QGIS` and `Designer` from the finder, but for none of them a GUI window appeared.  
Screenshot 2020-12-19 at 23 29 45

**Comment by gillins** [comment]
@jakimowb I don't know enough about OSX to comment - has anyone else see this? Does `qgis --help` work on the command line? That seems to succeed in the tests.

**Comment by SrNetoChan** [comment]
I have created a Hackintosh virtual machine to try this out. I was able to run QGIS GUI. But it is missing a bunch of functionality, like the processing toolbox and python console, several data source providers. I wasn't able to test it correctly because the menus weren't working either. But I am unsure if it was due to the use f a hacked SO or not. I will try to compare the environment with the Linux one to see what is missing.
What version of OSX are you using @jakimowb? are you creating a new environment for QGIS installation?

**Comment by jakimowb** [comment]
Thanks for the hint, I now installed it into the conda base/default environment, and everything seems to be fine there: GUI becomes visible, processing toolbox is available, I installed scipy + scikit-learn in conda and both can be imported in the QGIS python shell.

So for, it just seems to be a problem in new environments, in which @gillins `qgis --help`works fine, but still the GUI does not show up.

@SrNetoChan for testing I use this plattform: 

| Type | Value |
| ----------- | --------- |
| macOS  | Big Sur version 11.1 | 
| Model Name 	| MacBook Pro |
| Model Identifier |	MacBookPro16,3 |
| Processor Name |	Quad-Core Intel Core i5 |
| Processor Speed |	1,4 GHz |
| Number of Processors |	1 |
| Total Number of Cores |	4 |
| L2 Cache (per Core) |	256 KB |
| L3 Cache |	6 MB |
| Hyper-Threading Technology |	Enabled |
| Memory |	8 GB |

**Comment by SrNetoChan** [comment]
> Thanks for the hint, I now installed it into the conda base/default environment, and everything seems to be fine there: GUI becomes visible, processing toolbox is available, I installed scipy + scikit-learn in conda and both can be imported in the QGIS python shell.
> 
> So for, it just seems to be a problem in new environments, in which @gillins `qgis --help`works fine, but still the GUI does not show up.
> 
> @SrNetoChan for testing I use this plattform: 
> 
> | Type | Value |
> | ----------- | --------- |
> | macOS  | Big Sur version 11.1 | 
> | Model Name 	| MacBook Pro |
> | Model Identifier |	MacBookPro16,3 |
> | Processor Name |	Quad-Core Intel Core i5 |
> | Processor Speed |	1,4 GHz |
> | Number of Processors |	1 |
> | Total Number of Cores |	4 |
> | L2 Cache (per Core) |	256 KB |
> | L3 Cache |	6 MB |
> | Hyper-Threading Technology |	Enabled |
> | Memory |	8 GB |
> 

Good to hear. This means my hackingtosh is not suite to understand if things run ok or not!

**Comment by gillins** [comment]
@jakimowb are we missing a dependency that is available in your base environment? Can you see anything obvious?

I have an old Mac mini somewhere that hasn't been run for years, will try and get it going when I get a chance and investigate.

**Comment by SrNetoChan** [comment]
@jakimowb could you run

conda list

In both environments?

**Comment by jakimowb** [comment]
Sorry for my response time, you know, Christmas etc. 

I can run `conda list` in both environments. This is the difference between the running conda default and the extra environment (ironically) called `qgis_stable`:


````
--- list_base.txt	2020-12-23 14:07:54.000000000 +0100
+++ list_qgis.txt	2020-12-23 14:08:18.000000000 +0100
@@ -1,142 +1,139 @@
-# packages in environment at /Users/jakimowb/miniconda3:
+# packages in environment at /Users/jakimowb/miniconda3/envs/qgis_stable:
 #
 # Name                    Version                   Build  Channel
-boost-cpp                 1.72.0               hdf9ef73_0    conda-forge
-brotlipy                  0.7.0           py38h9ed2024_1003  
+boost-cpp                 1.74.0               he5d75e3_0    conda-forge
+brotlipy                  0.7.0           py38h94c058a_1001    conda-forge
 bzip2                     1.0.8                hc929b4f_4    conda-forge
 c-ares                    1.17.1               hc929b4f_0    conda-forge
 ca-certificates           2020.12.5            h033912b_0    conda-forge
-cairo                     1.16.0            hec6a9b0_1003    conda-forge
+cairo                     1.16.0            he8db5a5_1006    conda-forge
 certifi                   2020.12.5        py38h50d1736_0    conda-forge
-cffi                      1.14.4           py38h2125817_0  
-cfitsio                   3.470                h422484a_7    conda-forge
-chardet                   3.0.4           py38hecd8cb5_1003  
-conda                     4.9.2            py38h50d1736_0    conda-forge
-conda-package-handling    1.7.2            py38h22f3db7_0  
-coverage                  5.3.1            py38h5406a74_0    conda-forge
-cryptography              3.2.1            py38hbcfaee0_1  
+cffi                      1.14.4           py38h979bc6b_1    conda-forge
+cfitsio                   3.470                h01dc385_7    conda-forge
+chardet                   4.0.0            py38h50d1736_0    conda-forge
+coverage                  5.3              py38h5406a74_1    conda-forge
+cryptography              3.3.1            py38h6b4ec92_0    conda-forge
 curl                      7.71.1               hcb81553_8    conda-forge
-dbus                      1.13.6               h2f22bb5_0    conda-forge
+dbus                      1.13.6               h0c50699_1    conda-forge
 exiv2                     0.27.1               ha4feea6_0    conda-forge
-expat                     2.2.9                h4a8c4bd_2    conda-forge
-fontconfig                2.13.1            h6b1039f_1001    conda-forge
+expat                     2.2.9                hb1e8313_2    conda-forge
+fontconfig                2.13.1            h186bf41_1002    conda-forge
 freetype                  2.10.4               h3f75d11_0    conda-forge
 freexl                    1.0.5             h0b31af3_1002    conda-forge
 future                    0.18.2           py38h50d1736_2    conda-forge
-gdal                      3.1.1            py38h9f7df5a_0    conda-forge
+gdal                      3.1.4            py38hdf98abe_0    conda-forge
 geos                      3.8.1                h4a8c4bd_0    conda-forge
-geotiff                   1.6.0                hd8796ba_0    conda-forge
+geotiff                   1.6.0                hc1004f4_3    conda-forge
 gettext                   0.19.8.1          h7937167_1005    conda-forge
 giflib                    5.2.1                hbcb3906_2    conda-forge
-glib                      2.66.1               h9bbe63b_0  
+glib                      2.66.4               h22858aa_1    conda-forge
 gsl                       2.6                  h71c5fe9_1    conda-forge
-hdf4                      4.2.13            h84186c3_1003    conda-forge
-hdf5                      1.10.6          nompi_h3e39495_100    conda-forge
+hdf4                      4.2.13            h71d84a9_1004    conda-forge
+hdf5                      1.10.6          nompi_h0f9794f_1112    conda-forge
 httplib2                  0.18.1             pyh9f0ad1d_0    conda-forge
-icu                       64.2                 h6de7cb9_1    conda-forge
-idna                      2.10                       py_0  
+icu                       67.1                 hb1e8313_0    conda-forge
+idna                      2.10               pyh9f0ad1d_0    conda-forge
 jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
-joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
 jpeg                      9d                   hbcb3906_0    conda-forge
 json-c                    0.13.1            h575e443_1002    conda-forge
-kealib                    1.4.13               h40102fb_1    conda-forge
-krb5                      1.17.1               h14dd6a4_2    conda-forge
+kealib                    1.4.14               h82515a5_0    conda-forge
+krb5                      1.17.2               h60d9502_0    conda-forge
 libblas                   3.9.0                3_openblas    conda-forge
 libcblas                  3.9.0                3_openblas    conda-forge
-libclang                  9.0.1           default_hf57f61e_0    conda-forge
+libclang                  10.0.1          default_hf57f61e_1    conda-forge
 libcurl                   7.71.1               h9bf37e3_8    conda-forge
-libcxx                    10.0.0                        1  
+libcxx                    11.0.0               h4c3b8ed_1    conda-forge
 libdap4                   3.20.6               h993cace_1    conda-forge
-libedit                   3.1.20191231         h1de35cc_1  
+libedit                   3.1.20191231         h0678c8f_2    conda-forge
 libev                     4.33                 haf1e3a3_1    conda-forge
-libffi                    3.3                  hb1e8313_2  
-libgdal                   3.1.1                he0622db_0    conda-forge
-libgfortran               4.0.0               h1a10cd1_14    conda-forge
-libgfortran4              7.5.0               h1a10cd1_14    conda-forge
+libffi                    3.3                  h046ec9c_2    conda-forge
+libgdal                   3.1.4                hd7bf8dc_0    conda-forge
+libgfortran               5.0.0               h7cc5361_13    conda-forge
+libgfortran5              9.3.0               h7cc5361_13    conda-forge
+libglib                   2.66.4               h7424822_1    conda-forge
 libiconv                  1.16                 haf1e3a3_0    conda-forge
-libkml                    1.3.0             h169b8f9_1011    conda-forge
+libkml                    1.3.0             h8ca2c65_1012    conda-forge
 liblapack                 3.9.0                3_openblas    conda-forge
-libllvm9                  9.0.1                h7475705_1    conda-forge
+libllvm10                 10.0.1               h009f743_3    conda-forge
 libnetcdf                 4.7.4           nompi_h9d8a93f_107    conda-forge
-libnghttp2                1.41.0               h8a08a2b_1    conda-forge
-libopenblas               0.3.12          openmp_h63d9170_1    conda-forge
+libnghttp2                1.41.0               h7580e61_2    conda-forge
+libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
 libpng                    1.6.37               h7cec526_2    conda-forge
 libpq                     12.3                 h7049927_3    conda-forge
-libprotobuf               3.11.4               hd174df1_0    conda-forge
+libprotobuf               3.13.0.1             hab81aa3_0    conda-forge
 libspatialindex           1.9.3                h4a8c4bd_3    conda-forge
-libspatialite             4.3.0a            h658e6c1_1038    conda-forge
+libspatialite             5.0.0                hc85de81_0    conda-forge
 libssh2                   1.9.0                h8a08a2b_5    conda-forge
 libtasn1                  4.14                 h01d97ff_0    conda-forge
-libtiff                   4.1.0                h2ae36a8_6    conda-forge
+libtiff                   4.1.0                hca7d577_6    conda-forge
+libwebp                   1.1.0                hd89b0c2_4    conda-forge
 libwebp-base              1.1.0                hbcb3906_3    conda-forge
-libxml2                   2.9.10               h53d96d6_0    conda-forge
+libxml2                   2.9.10               h2c6e4a5_2    conda-forge
+libxslt                   1.1.33               hfed2d9b_1    conda-forge
 libzip                    1.7.3                h815a1b3_0    conda-forge
 llvm-openmp               11.0.0               h73239a0_1    conda-forge
-lz4-c                     1.9.2                h4a8c4bd_1    conda-forge
+lz4-c                     1.9.2                hb1e8313_3    conda-forge
 markupsafe                1.1.1            py38h94c058a_2    conda-forge
 mock                      4.0.3            py38h50d1736_0    conda-forge
-ncurses                   6.2                  h0a44026_1  
+mysql-common              8.0.21                        2    conda-forge
+mysql-libs                8.0.21               hfb8f7af_2    conda-forge
+ncurses                   6.2                  h2e338ed_4    conda-forge
 nose2                     0.9.2                      py_0    conda-forge
-nspr                      4.20              h0a44026_1000    conda-forge
+nspr                      4.29                 hb1e8313_1    conda-forge
 nss                       3.47                 hc0980d9_0    conda-forge
 numpy                     1.19.4           py38h6ced74f_2    conda-forge
-openjpeg                  2.3.1                h254dc36_3    conda-forge
+openjpeg                  2.3.1                h6cbf5cd_3    conda-forge
 openssl                   1.1.1i               h35c211d_0    conda-forge
 owslib                    0.21.0             pyhd8ed1ab_0    conda-forge
-pcre                      8.44                 h4a8c4bd_0    conda-forge
+pcre                      8.44                 hb1e8313_0    conda-forge
 pip                       20.3.3             pyhd8ed1ab_0    conda-forge
-pixman                    0.38.0            h01d97ff_1003    conda-forge
+pixman                    0.40.0               hbcb3906_0    conda-forge
 plotly                    4.14.1             pyhd3deb0d_0    conda-forge
 poppler                   0.89.0               h3232a60_1    conda-forge
 poppler-data              0.4.10                        0    conda-forge
 postgresql                12.3                 he852019_3    conda-forge
-proj                      7.0.0                h45baca5_5    conda-forge
+proj                      7.1.1                h45baca5_3    conda-forge
 psycopg2                  2.8.6            py38h52adbb4_1    conda-forge
-pycosat                   0.6.3            py38h1de35cc_1  
-pycparser                 2.20                       py_2  
+pycparser                 2.20               pyh9f0ad1d_2    conda-forge
 pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
-pyopenssl                 20.0.0             pyhd3eb1b0_1  
-pyproj                    2.6.1.post1      py38h7d7e87d_0    conda-forge
-pyqt                      5.12.3           py38hf180056_3    conda-forge
-pyqt5-sip                 4.19.18                  pypi_0    pypi
-pyqtchart                 5.12                     pypi_0    pypi
-pyqtwebengine             5.12.1                   pypi_0    pypi
-pysocks                   1.7.1                    py38_1  
-python                    3.8.3                h26836e1_1  
+pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
+pyproj                    2.6.1.post1      py38h4367d1d_3    conda-forge
+pyqt                      5.12.3           py38h50d1736_6    conda-forge
+pyqt-impl                 5.12.3           py38h721a93c_6    conda-forge
+pyqt5-sip                 4.19.18          py38h5745d40_6    conda-forge
+pyqtchart                 5.12             py38h721a93c_6    conda-forge
+pyqtwebengine             5.12.1           py38h721a93c_6    conda-forge
+pyqtwebkit                5.212            py38h50d6cb5_1    conda-forge
+pysocks                   1.7.1            py38h5347e94_2    conda-forge
+python                    3.8.6           h3b7b5d6_1_cpython    conda-forge
 python-dateutil           2.8.1                      py_0    conda-forge
-python.app                2                       py38_10  
 python_abi                3.8                      1_cp38    conda-forge
 pytz                      2020.4             pyhd8ed1ab_0    conda-forge
 pyyaml                    5.3.1            py38h94c058a_1    conda-forge
 qca                       2.2.1                hc763db3_3    conda-forge
-qgis                      3.14.0           py38h1f41940_1    conda-forge
+qgis                      3.16.1           py38h03ef37c_2    conda-forge
 qjson                     0.9.0             hc763db3_1006    conda-forge
-qscintilla2               2.11.2           py38h2815f34_2    conda-forge
-qt                        5.12.5               h514805e_3    conda-forge
-qtkeychain                0.10.0               h2815f34_0    conda-forge
-qtlocation                5.12.5               h4a8c4bd_0    conda-forge
+qscintilla2               2.11.2           py38h9d533bb_4    conda-forge
+qt                        5.12.9               h717870c_0    conda-forge
+qtkeychain                0.11.1               h80aacfe_0    conda-forge
+qtlocation                5.12.9               hb1e8313_0    conda-forge
 qtserialport              5.9.8                hc763db3_1    conda-forge
+qtwebkit                  5.212                hfa2e8d5_0    conda-forge
 qwt                       6.1.5                h2815f34_0    conda-forge
 qwtpolar                  1.1.1                h2815f34_7    conda-forge
-readline                  8.0                  h1de35cc_0  
-requests                  2.25.0             pyhd3eb1b0_0  
+readline                  8.0                  h0678c8f_2    conda-forge
+requests                  2.25.1             pyhd3deb0d_0    conda-forge
 retrying                  1.3.3                      py_2    conda-forge
-ruamel_yaml               0.15.87          py38haf1e3a3_1  
-scikit-learn              0.22.1           py38h3dc85bc_1    conda-forge
-scipy                     1.4.1            py38h38b60c6_3    conda-forge
-setuptools                50.3.1           py38hecd8cb5_1  
-sip                       4.19.23          py38hc84c608_0    conda-forge
-six                       1.15.0           py38hecd8cb5_0  
-sqlite                    3.33.0               hffcf06c_0  
-tbb                       2019.9               ha1b3eb9_1    conda-forge
-tiledb                    2.0.6                h84aa2a7_0    conda-forge
-tk                        8.6.10               hb0a8c7a_0  
-tqdm                      4.51.0             pyhd3eb1b0_0  
+setuptools                49.6.0           py38h5347e94_2    conda-forge
+six                       1.15.0             pyh9f0ad1d_0    conda-forge
+sqlite                    3.34.0               h17101e1_0    conda-forge
+tiledb                    2.1.3                h77aa7c5_0    conda-forge
+tk                        8.6.10               h0419947_1    conda-forge
 tzcode                    2020d                h35c211d_0    conda-forge
-urllib3                   1.25.11                    py_0  
+urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
 wheel                     0.36.2             pyhd3deb0d_0    conda-forge
-xerces-c                  3.2.2             h8f8adb3_1004    conda-forge
-xz                        5.2.5                h1de35cc_0  
-yaml                      0.2.5                haf1e3a3_0  
-zlib                      1.2.11               h1de35cc_3  
-zstd                      1.4.5                h0384e3a_1    conda-forge
+xerces-c                  3.2.3                h0a0444a_1    conda-forge
+xz                        5.2.5                haf1e3a3_1    conda-forge
+yaml                      0.2.5                haf1e3a3_0    conda-forge
+zlib                      1.2.11            h7795811_1010    conda-forge
+zstd                      1.4.5                h289c70a_2    conda-forge
````

**Comment by gillins** [comment]
Thanks @jakimowb I notice you have an older `qt` and `qgis` in your base environment - I wonder if you would see the same thing in the base environment if you upgraded to be the same version?

I did some googling and it appears other people are seeing this with Big Sur (https://forum.qt.io/topic/119316/mac-application-built-with-5-12-9-lts-hangs-on-launch-under-big-sur and https://stackoverflow.com/questions/64833558/apps-not-popping-up-on-macos-big-sur-11-0-1#_=) 

Seems some people are reporting success with setting this env var: `QT_MAC_WANTS_LAYER=1`. Can you try running:
```
export QT_MAC_WANTS_LAYER=1
```
before running `qgis` and see what happens?

BTW My ancient Mac Mini is stuck on 10.11 so I can't even test modern Qt apps (need 10.12) so I'm probably not going to be much help. I wonder if we need to wait for a new Qt?

**Comment by jakimowb** [comment]
@gillins thanks, with `export QT_MAC_WANTS_LAYER=1` I can start it (see table below) 

However, there are still some problems:
1. This error is raised during startup: 
  `2020-12-29T12:14:11     CRITICAL    Authentication System : DISABLED. Resources authenticating via the system can not be accessed`

2. QGIS Resources, like internal plugins or the `world_map.gpkg` are not available. The QGIS.app expects them in: 
`<conda directory>/envs/qgis_stable/QGIS.app/Contents/MacOS/share/qgis/resources/data/world_map.gpkg`, but they while `share` is installed to 
`<conda directory>envs/qgis_stable/share/qgis/resources/data/world_map.gpkg`. 
  Seems the QGIS prefix path need to be fixed.


QGIS version | 3.16.1-Hannover | QGIS code branch | Release 3.16
-- | -- | -- | --
Compiled against Qt | 5.12.9 | Running against Qt | 5.12.9
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.26.0 | Running against SQLite | 3.34.0
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 5.0.0
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.1.1 | Running against PROJ | Rel. 7.1.1, September 1st, 2020
OS Version | macOS 10.16




`2020-12-29T12:11:45     CRITICAL    Authentication System : DISABLED. Resources authenticating via the system can not be accessed`

**Pull request merged**
