### PR TITLE
Update 3.20

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@SrNetoChan I think removing all the patches *should* allow this one to build (have been pushed upstream)....

**Comment by SrNetoChan** [comment]
Thanks @gillins I will try that.

**Comment by SrNetoChan** [comment]
@gillins It seems that in general, QGIS 3.20 won't work with 3.16 (Linux, Windows and Mac), then are different consistent issues in each OS. I am guessing that new patches will lbe needed, or maybe some need to be added back.

**Comment by gillins** [comment]
Ok will have a look when i get a chance

**Comment by SrNetoChan** [comment]
Ok, got it confirmed python 3.16 is no longer supported.

https://github.com/qgis/QGIS/pull/41778

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
Anyone know what is going on here? Error is:
```
sip: core/auto_generated/qgis.sip:214: There is already an enum member in scope with the same Python name
```

Seems `Success` is defined twice (line 83 and 214). Not sure if I'm missing something here...

**Comment by kmuehlbauer** [comment]
@gillins I've no real idea either. The first definition is inside a common `enum` not in an `enum  class`. Maybe it's just some compiler switch which treats that as an error, sorry, I do not know what I'm saying, just guessing.

**Comment by gillins** [comment]
Seems `VectorExportResult` was added in this commit: https://github.com/qgis/QGIS/commit/de406693c76bae650967068a193906e08794d88d#diff-bc50728d98a7ec8e1fe2bd5609c6f72faed45b94d5e8976d2641d1d141281e6f
So it wasn't there in the previous release...

**Comment by kmuehlbauer** [comment]
Yes, and they changed the name from "NoError" to "Success" (https://github.com/qgis/QGIS/commit/de406693c76bae650967068a193906e08794d88d). But why did it not fail upstream. Some compiler switches or sip version?

**Comment by kmuehlbauer** [comment]
@gillins Maybe they missed that one in here: https://github.com/qgis/QGIS/pull/43269

**Comment by kmuehlbauer** [comment]
Seems qgis did this intentional because of sip issues: https://github.com/qgis/QGIS/pull/43443

@nyalldawson We appreciate any hints on how to get us going here. We have an error about  enum redeclaration, see  (https://github.com/conda-forge/qgis-feedstock/pull/194#issuecomment-868266801) and following comments. Thanks.

**Comment by nyalldawson** [comment]
Which python and sip versions are you using? We bumped things aggressively for 3.20 in order to get access to newer functionality we wanted (such as enum classes, which work poorly/are broken  in older sip versions)

**Comment by kmuehlbauer** [comment]
Thanks @nyalldawson. According to the logs, we use sip 4.9.18 for the linux builds with python 3.7.10, 3.8.10, 3.9.5. I've checked with QGIS-logs, you are using sip 4.19.21, right? Could that be the issue?

**Comment by nyalldawson** [comment]
> According to the logs, we use sip 4.9.18 for the linux builds with python 3.7.10, 3.8.10, 3.9.5. I've checked with QGIS-logs, you are using sip 4.19.21, right? Could that be the issue?

It could be... But @3nids would know better than me!

**Comment by 3nids** [comment]
Yes I believe upgrading to sip 4.19.21 should fix the issues. That is basically Ubuntu 20.04.

**Comment by kmuehlbauer** [comment]
@3nids Thanks for clarifying. Just one more question, I've seen that sip 4.19.25 is the last supported version 4. Are you already testing later versions? Any pointers to discussions at QGIS are appreciated.

**Comment by kmuehlbauer** [comment]
@gillins, @SrNetoChan Uh-oh, that will be a major pain to get sorted out. AFAIK, the sip we use gets build and shipped alongside `pyqt` (https://github.com/conda-forge/pyqt-feedstock/blob/master/recipe/meta.yaml). Not sure, if we can just use the other sip (https://github.com/conda-forge/sip-feedstock) or if pyqt would have to be rebuild with the later version.

**Comment by SrNetoChan** [comment]
I saw that conda-forge moved from 16.04 to latest version of ubuntu for linux builds "recently".  That can also bring some extra pain.

Anyway, I am clueless... I am a nullity regarding all the building process... I just try to set things running, and then count with the countless efforts from @gillins and @ocefpaf  :-)

**Comment by gillins** [comment]
I actually had a go at updating `sip` a while ago (https://github.com/conda-forge/pyqt-feedstock/pull/94) but found newer versions didn't work with our older Qt/PyQt. Maybe we need to wait until we have a newer Qt?

**Comment by kmuehlbauer** [comment]
@gillins Seems we are stuck here. So this has to be build up from starting with new qt version -> then new qtpy+sip and then qgis.

**Comment by gillins** [comment]
> Seems we are stuck here

That's my feeling. Seems that a new Qt isn't that far away anyway: https://github.com/conda-forge/qt-feedstock/issues/192#issuecomment-861027937. If someone wants to experiment with a newer `sip` with the current stack, feel free but I don't think I have the energy ATM...

**Comment by nyalldawson** [comment]
Sorry about that -- we knew the dependency bump was quite aggressive, but it was never the intention to block the conda builds! (The thinking was that users on older Linux distros.could stick with the 3.16 ltr release (which is a great release), but obviously that doesn't apply here...)

**Comment by SrNetoChan** [comment]
Thank you guys for looking into this. If I understand correctly, we need to update the sip all the way from qt? (Just so that I better understand the process)

**Comment by SrNetoChan** [comment]
> Sorry about that -- we knew the dependency bump was quite aggressive, but it was never the intention to block the conda builds! (The thinking was that users on older Linux distros.could stick with the 3.16 ltr release (which is a great release), but obviously that doesn't apply here...)

Actually, we maintain an LTR branch so that's still an option, I guess.

**Comment by gillins** [comment]
> If I understand correctly, we need to update the sip all the way from qt?

I \*think\* so. I don't think we can update `sip` without a newer `qt`. Our `qt` is laughably old (5.12.9) and that's already caused us trouble (remember that issue with OSX BigSur - someone eventually backported a fix). I'm not really surprised that `qgis` requires us to have a newer stack.
I understand that work to get `qt` 5.15 (the last of the 5.x series) into conda-forge is close to being complete so my feeling is that it's best to wait for this and have another go. Let's just maintain the LTS branch in the meantime. 
I'm no expert in `qt` though, so if anyone with has differing thoughts please jump in!

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by danschef** [comment]
Could someone provide a brief update on the developments here? We are trying to make some strategic decisions on our side (support for QGIS 3.18 gets more and more dropped in some packages) and it is not clear if it makes sense to hope for a current QGIS release on conda-forge, especially behind the background that the QT 5.15 developments seem to have stopped here (at least https://github.com/conda-forge/qt-feedstock/pull/206 was closed) and there are apparently some license issues with QT LTS releases (https://github.com/conda-forge/qt-feedstock/issues/200).

**Comment by gillins** [comment]
> Could someone provide a brief update on the developments here?

We are indeed waiting for a new `qt` before we can upgrade the version of `qgis`. However, there is active work on later `qt` versions in this feedstock: https://github.com/conda-forge/qt-main-feedstock/. Once other feedstocks (like `pyqt`, `qtwebengine` etc) are rebuilt against `qt-main`, we should be in a position to update. Can't provide any timeline for when that might happen though...

**Pull request closed without merging**
