### PR TITLE
remove pyqtwebkit dependency

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by SrNetoChan** [comment]
We really need pyqtwebkit for qgis to work properly.

**Comment by SrNetoChan** [comment]
Check the comments on this 3y old issue:

https://github.com/conda-forge/qgis-feedstock/issues/68

**Comment by bnavigator** [comment]
You should really make it an effort to NOT require pyqtwebkit.

https://github.com/conda-forge/pyqt-feedstock/pull/117#issuecomment-1206885735

Adding `-DWITH_QTWEBKIT=FALSE` should be enough. Citing a 3 year old issue (#68) without checking the relevance for a current QGIS does not help.

**Comment by gillins** [comment]
@nyalldawson is this still the case? Do we still need QtWebKit to build `qgis` properly?

**Comment by nyalldawson** [comment]
@gillins 

Still the case, yes. 

I spent some time looking into qt webengine again this week and the whole situation is still a flaming 💩. We can't use we engine without initialising an OpenGL context before creating the application, but doing so breaks compatibility with qt3d. So we have a mutually exclusive choice of the qgis 3d framework or webengine support.

Suffice to say, there's no plans anywhere on the horizon to remove this dependency.

**Comment by izahn** [comment]
> I spent some time looking into qt webengine again this week 

We're talking about `qtwebkit` here, not `qtwebengine`, can you clarify which one you looked into?

**Comment by bnavigator** [comment]
@izahn qtwebengine is the "replacement" of qtwebkit for webviews

**Comment by izahn** [comment]
Oh I see you guys are talking about removing the `pyqtwebkit` dependency in QGIS itself, not just disabling it in the conda-forge build.

**Comment by gillins** [comment]
> Oh I see you guys are talking about removing the pyqtwebkit dependency in QGIS itself, not just disabling it in the conda-forge build.

Yes that's right. What I think @nyalldawson (thanks for replying btw) is saying is that a build of QGIS without pyqtwebkit wouldn't have all of the QGIS features enabled....
So we can either remove pyqtwebkit and have a build without all features enabled, or continue to build against pyqtwebkit.

**Comment by nyalldawson** [comment]
> So we can either remove pyqtwebkit and have a build without all features enabled, or continue to build against pyqtwebkit.

That's correct. And that there's no alternative in sight yet. Ultimately we'd love to replace WebKit with web engine, but we just can't until qt upstream fixes the whole situation up.

**Comment by SrNetoChan** [comment]
Can we close this one?

**Comment by gillins** [comment]
Yep!

**Pull request closed without merging**
