### PR TITLE
Try new version of pyqt-sip

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@gillins it seems it picked up the new pyqt-sip and sip. Let's see if it builds a d if it passes the tests 🤞

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
It worked!

**Pull request merged**
