### PR TITLE
Update LTR to 3.10.4

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@ocefpaf @gillins Any idea why only Python3.7 on OSX is failing?

**Comment by ocefpaf** [comment]
> @ocefpaf @gillins Any idea why only Python3.7 on OSX is failing?

The logs are no longer there. (Azure is terrible b/c they erase the logs way too quickly.)

**Comment by SrNetoChan** [comment]
Probably my fault as I asked for rebuild

**Comment by ocefpaf** [comment]
> Probably my fault as I asked for rebuild

Not really. A Robust CI service should keep logs for as much we we need and for as many rebuilds we need. Otherwise what is the point? How can we track it? AzurePipelines needs to improve that.

**Pull request merged**
