### PR TITLE
Update to 3.0.3

### PR DESCRIPTION
**Pull request by SrNetoChan**
Bumped qgis version to 3.0.3 and removed the skip to linux

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@ocefpaf  Sorry to bother. Now windows tests are passing, this would update windows version to 3.0.3.

I was also trying to make it build on linux as well. The recipe works locally, but I was not able to make it run travis tests in here. I guess it probably won't build qgis 3.0.3 for Linux in that case.

**Comment by ocefpaf** [comment]
No problem @SrNetoChan. But I'll leave this one open for @ceholden and @gillins to take a look.

PS: can you open an issue for the Linux problem or paste it here?

**Comment by SrNetoChan** [comment]
@ocefpaf the problem is me :) I don't know how to trigger the Linux build/test. This recipe works well locally for linux, but maybe there is something missing that would trigger Travis.

**Comment by gillins** [comment]
You will need to re-render to get Linux (after removing the skip). FYI @ceholden ran into a nasty problem with the version of `gcc` that conda uses and QGIS  - see https://github.com/conda-forge/qgis-feedstock/issues/17#issuecomment-373222272.

**Comment by gillins** [comment]
@ocefpaf would it make sense to update this to the "new" format so we get `gcc` 7.2 and workaround the build problem on Linux?

**Comment by ocefpaf** [comment]
> @ocefpaf would it make sense to update this to the "new" format so we get `gcc` 7.2 and workaround the build problem on Linux?

The new format won't use the new compilers, yet.
But we do need to take that step before activating the compilers.

The bot is actually doing that but you can do that with latest `conda-smithy`.
If you want to give it a go try:

```shell
conda smithy update-cb3
```

Not that to take advantage of the `run_export` stuff we need to wait for the recipes to be compiled in the right order. (See @msarahan comment on `kealib`.)

**Comment by SrNetoChan** [comment]
@ocefpaf @gillins I have run `smithy update-cb3` (https://github.com/conda-forge/qgis-feedstock/pull/36/commits/9731d9a00881a79c35144bf0dc68dc29fd7c8b86). It has removed all tge dependencies versions. Is that supposed on the new format? Do we have to put them back?

**Comment by ocefpaf** [comment]
> @ocefpaf @gillins I have run `smithy update-cb3` (https://github.com/conda-forge/qgis-feedstock/pull/36/commits/9731d9a00881a79c35144bf0dc68dc29fd7c8b86). It has removed all tge dependencies versions. Is that supposed on the new format?

Yes b/c the Software pinnings are now defined in the `yaml` files like this one:

https://github.com/SrNetoChan/qgis-feedstock/blob/42fd55f328cc28f9914206f42a8adf25aace2b6e/.ci_support/linux_python3.5.yaml

> Do we have to put them back?

Only if the pinnings disagrees with the ones in that file. And even in that case we must have a strong reason to do so.

However, I would not recommend the new format for such a complex recipe just yet.
It is a desirable change, but we should probably start with some low hanging fruit, define the `run_exports` in the dependencies, and then tackle `qgis`.

**Comment by SrNetoChan** [comment]
@ocefpaf 
> However, I would not recommend the new format for such a complex recipe just yet.
> It is a desirable change, but we should probably start with some low hanging fruit, define the run_exports in the dependencies, and then tackle qgis.

In that case, I will revert that commit.

Sorry for the dumb questions, I don't really understand all of this.

Thanks

**Comment by ocefpaf** [comment]
> Sorry for the dumb questions,

There are no dumb questions. `conda-forge ` has many moving parts and no one is on top of everything.

>  I don't really understand all of this.

I don't think any of us does :smile:

**Comment by kmuehlbauer** [comment]
@SrNetoChan @ocefpaf Any news on this? What is the blocking issue here? If I can be of any help, let me know.

**Comment by SrNetoChan** [comment]
@kmuehlbauer Tests are failing for Python. I wasn't able to figure out what was wrong.

**Comment by kmuehlbauer** [comment]
@SrNetoChan Thanks for responding. Looking at the build-logs it seems not to find `libspatialite`, although it has version `4.3.0`. I'll investigate locally.

**Comment by ocefpaf** [comment]
@kmuehlbauer and @SrNetoChan this may be related to https://github.com/conda-forge/conda-forge.github.io/issues/621

I'm re-building everything without the `.la` files but this will take a while :-(

**Comment by kmuehlbauer** [comment]
@ocefpaf I tried qgis v.3.2.2 locally with @SrNetoChan branch. Then I got an other error. In the env compilers from default were pulled in.

**Comment by ocefpaf** [comment]
> @ocefpaf I tried qgis v.3.2.2 locally with @SrNetoChan branch. Then I got an other error. In the env compilers from default were pulled in. 

We are at transition point in `conda-forge` to get the new compilers going so building locally is not an easy task. I recommend using the docker image and build with the command:

```shell
conda build recipe -m .ci_support/linux_.yaml  # <- file file may have different names depending on the build.
```

**Comment by ceholden** [comment]
Sorry to be missing on these PRs (I really needed to finish my PhD!!), and thanks for your work trying to get 3.0 going and the updates to the 2.18 series.

I just merged an update to QGIS 3.4 and should've asked beforehand, but would you be interested in being maintainers @kmuehlbauer and @SrNetoChan?

**Comment by kmuehlbauer** [comment]
@ceholden Thanks for putting that last version up. I did not had the time to investigate  more, unfortunately. I'm not using QGIS regularly, but I need it for specific tasks. I'm thinking about implementing some of my workflows into QGIS plugins. So if I can be of any help here, yes just add me as maintainer.

**Comment by SrNetoChan** [comment]
@ceholden I don't mind being a maintainer, but normally I won't be able to do much more than bumping the version. That's why I got stuck.

**Pull request closed without merging**
