### PR TITLE
Update main to 3.30.0

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@gillins both 3.30 and 3.28 are facing the same issue. It seems pyqt5 could not be found. I tried to debug this yesterday in a VM machine but it was crashing (my vm is probably not good enough). Any ideas?

**Comment by SrNetoChan** [comment]
The only relevant change I saw was in windows virtual machine that is used. do you think we need to rerender pyqt?

Didn't saw any relevant changes upstream either.

**Comment by gillins** [comment]
I saw the same issue with that PPC PR, but didn't investigate. Something must have changed recently. I'll do a bit of digging when I get a moment.

**Comment by SrNetoChan** [comment]
Maybe pyqt needs to be rerendered?

**Comment by gillins** [comment]
No idea. I'll try and add some messages to the output to see what is going wrong first.

**Comment by gillins** [comment]
This is my bad because there are 2 copies of `PyQt5-5.15.*.dist-info/METADATA`. One for 5.15.9 from `pyqtwebkit` (I had to merge this later version to fix OSX arm64) and one for 5.15.7 from `pyqt` (migration to 5.15.9 is stalled here: https://github.com/conda-forge/pyqt-feedstock/pull/129).
I'll see if I can do a workaround.

**Pull request merged**
