### PR TITLE
upload to LTR builds qgis_ltr label

### PR DESCRIPTION
**Pull request by gillins**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/qgis-feedstock/issues/425.

@ocefpaf is this what you meant?

Do I have to add a `conda config --env --add channels qgis_ltr` to the post install? Or is that not necessary?

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> @ocefpaf is this what you meant?

Yep.
 
> Do I have to add a `conda config --env --add channels qgis_ltr` to the post install? Or is that not necessary?

That is not needed. The error here is unrelated to the PR. Something broken in the CIs configuration but I believe it was already fixed. Restarting the CIs here to check.

**Comment by gillins** [comment]
Thanks @ocefpaf. Looks all good now. How will we publicize this change?

Are you happy with this @SrNetoChan @petrushy ?

**Comment by petrushy** [comment]
Many thanks! Looks good!

**Comment by ocefpaf** [comment]
> How will we publicize this change?

I guess that is the hardest part. We do have a blog for announcements but I doubt that will reach qgis conda users.

**Comment by SrNetoChan** [comment]
What's the difference? How do we install qgis ltr now? I can update my blog post about it. I also wanted to add conda installation procedure on qgis website, maybe that's the perfect time for it.

**Comment by SrNetoChan** [comment]
Will it be?

   conda install -c conda-forge/label/qgis_ltr qgis ?

How about the update procedure? We will need to add the channel again? 

    conda update -conda-forge/label/qgis_ltr qgis

Is there a way  make qgis_ltr label the default for and environment?

This means that if I want to install a particular version of QGIS, that happens to have been a LTR, I will need to know it beforehad, otherwise it won't be available using the normal install (main label)?

**Comment by ocefpaf** [comment]
> Will it be?
> 
> `conda install -c conda-forge/label/qgis_ltr qgis` ?

That should work but I prefer,

```
conda install conda-forge/label/qgis_ltr::qgis
```

because it mimics how one adds it to an `environment.yaml` file.

However, I'm not sure that works in all conda's flavors, like micromamba, etc. So maybe it is safer to stick with your CLI there.


> How about the update procedure? We will need to add the channel again?
> 
> ```
> conda update -conda-forge/label/qgis_ltr qgis
> ```

That should work.

> Is there a way make qgis_ltr label the default for and environment?

Yes, one can add that to a .condarc. Something like:

```yaml
channels:
  - conda-forge/label/qgis_ltr
  - conda-forge
```

Should ensure that the LTR is preffered over the version in the main channel.
 
> This means that if I want to install a particular version of QGIS, that happens to have been a LTR, I will need to know it beforehad, otherwise it won't be available using the normal install (main label)?

Yes. You need to search, install, etc from the LTR label. A label is like a channel, just a trick to keep it under the same org name.

**Comment by gillins** [comment]
@SrNetoChan - merge this if/when you are happy

**Comment by SrNetoChan** [comment]
I have no strong feelings about this. But if others feel it's useful, why not? I wonder if we could/should add this conda-forge/label/qgis_ltr line in our post-install process. That way, from that point on, the update would be in line with the "normal" install.

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=c2VuaG9yLm5ldG9AZ21haWwuY29t>

**Comment by SrNetoChan** [comment]
Although, can the .condarc be edited for a specific environment?

**Comment by SrNetoChan** [comment]
I am merging this. Let's see how it works. Thanks @gillins and @ocefpaf

**Comment by SrNetoChan** [comment]
Ok. This worked pretty well. I did it this way:

    mamba create -n qgis_ltr
    mamba activate qgis_ltr
    conda config --env --add channels conda-forge/label/qgis_ltr
    mamba install qgis

the qgis packages was picked from the qgis_ltr label and all the rest from conda-forge.

**Comment by petrushy** [comment]
Works very well, I removed the qgis, added conda config --env --add channels conda-forge/label/qgis_ltr   and got the ltr version as expected.

Now conda update --all works (keeps the LTR version).

Many thanks for this feature!

**Pull request merged**
