### PR TITLE
Try force gdal 3.6.1 update

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
```
- Encountered problems while solving:
-   - package libgdal-3.6.1-h839a3bd_0 requires libpq >=15.1,<16.0a0, but none of the providers can be installed
- 
```
Weird, maybe this explains why new `qgis` envs end up with gdal 3.6.0? Not sure what needs to be re-rendered though, maybe postgres?

**Comment by SrNetoChan** [comment]
libpg-feedstock has been archived. Need to figure out where it is built now.

**Comment by gillins** [comment]
It's part of https://github.com/conda-forge/postgresql-feedstock/ I think

**Comment by SrNetoChan** [comment]
I was able to install gdal and libgdal 3.6.1 in a new environment and it's picking up libpg 15.1 without issues, so maybe something else is pushing libpg down?

**Comment by gillins** [comment]
could be pdal?

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
There was a `postgresql` pin in the `meta.yaml`... Removed and all seems ok. Merge if you are happy.

**Pull request merged**
