### PR TITLE
Update stable version to 3.14.0

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@ocefpaf @gillins @isuruf Any ideas of what is going on in here? The same is happening with the LTR candidate #130

**Comment by gillins** [comment]
It's the same problem mentioned here: https://github.com/conda-forge/qgis-feedstock/pull/124. So I think we are still waiting for a new `conda-build` then a new `pyqt` for this to be fixed....

**Comment by SrNetoChan** [comment]
> It's the same problem mentioned here: #124. So I think we are still waiting for a new `conda-build` then a new `pyqt` for this to be fixed....

I that can, I am kinda glad that I didn't use a fork earlier and QGIS is available at least for Linux and Mac.

**Comment by ocefpaf** [comment]
> I that can, I am kinda glad that I didn't use a fork earlier and QGIS is available at least for Linux and Mac.

Yep. But b/c the Windows problem is out of our hands at the moment I recommend we merge this without Windows to "cash in" Linux and macOS.

**Comment by SrNetoChan** [comment]
Let's do it then. Please notice that, because I messed up with the forks, there are already linux and mac packages available on conda.

Do we need to do anything else to clean it up?

**Comment by ocefpaf** [comment]
> Let's do it then. Please notice that, because I messed up with the forks, there are already linux and mac packages available on conda.

In that case let's leave this open so we can track the Windows failure.

> Do we need to do anything else to clean it up?

Nope.Those are working builds. We should be fine. Thanks!

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please restart ci

**Comment by ocefpaf** [comment]
@isuruf removing the bad pyqt and sip worked! Thanks!

Thanks @SrNetoChan for the PR and the patience! This one took longer than we expected.

**Pull request merged**
