### PR TITLE
update package to 2.18.20

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@ocefpaf @ceholden This branch started to fail on circleci after the merge of my last PR (although the PR was not failing the tests)

Also, it is building fine locally.

Any idea what may be the problem?

**Comment by ocefpaf** [comment]
It seems to be breaking here:

```
[ 59%] Linking CXX shared library ../../output/lib/libqgis_gui.so
[ 59%] Built target qgis_gui
make: *** [all] Error 2
```

I'll take a look later today.

PS: when you say locally do you mean with conda-forge's docker image or using your system libs? The former should reproduce the same breakage here but the latter may be using something installed in your computer.

**Comment by SrNetoChan** [comment]
@ocefpaf wrote

> PS: when you say locally do you mean with conda-forge's docker image or using your system libs? The former should reproduce the same breakage here but the latter may be using something installed in your computer.

The latter. So probably it pick up some dependency from elsewhere.

**Comment by ocefpaf** [comment]
> The latter. So probably it pick up some dependency from elsewhere.

Take a look at

https://conda-forge.org/docs/testing.html#docker-tests

for the docker image instructions. You can also mount it with

```
docker run --net=host -it --rm -v $(pwd):/home/ condaforge/linux-anvil /bin/sh
```

so you can make multiple tries in one go and debug things.

**Comment by ceholden** [comment]
QGIS2 looks to have stopped with release `2.18.28` on Feb 14, 2019 -- is there any desire to update to it?

There is a PR to update the [qt4 recipe to use conda-build 3](https://github.com/conda-forge/qt-feedstock/pull/94) so it might be eventually possible to put out a new QGIS2 if there's interest. Python 2 is unsupported soon enough though and personally I've resigned myself to just porting/rewriting all my QGIS2 relevant stuff.

**Comment by SrNetoChan** [comment]
I don't think we should keep maintaining a 2.18 version. And no point in wasting time with it. Let's focus on QGIS 3, 3.4 LTR and stable (3.6) if possible.

**Pull request closed without merging**
