### PR TITLE
Backports stable version fixes

### PR DESCRIPTION
**Pull request by SrNetoChan**
Backports OpenCL and qgis_processing fixes to LTR

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@conda-forge-admin, please restart ci​​

**Comment by gillins** [comment]
I think this is related to https://github.com/conda-forge/gdal-feedstock/pull/806, not really sure.

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
