### PR TITLE
Backport keep pyi files

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is not a crucial patch, nevertheless, keeping the pyi files will allow for some python text editors to use autocomplete
even on classes built on C++ 

This have been done in QGIS Master branch, the current patch kind of backports it to our LTR build

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please restart ci

**Comment by SrNetoChan** [comment]
@ocefpaf @gillins any idea why there are any checks running?

**Comment by gillins** [comment]
No, but this is also happening for `gdal` (https://github.com/conda-forge/gdal-feedstock/pull/510)...

**Comment by SrNetoChan** [comment]
And It should be happening in other feedstock. Someone should be on it.

**Comment by SrNetoChan** [comment]
@gillins it seems that's a azure status problem. But the builds are running so you can go directly the Azure's pages.

**Comment by SrNetoChan** [comment]
Everything seems ok:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=366137&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e

Is there a way to download the build artifacts? I would like to check if my change did something or not...

**Pull request merged**
