### PR TITLE
Migrate python3.10, gdal3.4, proj8.2, and geos3.10.1 at once

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Due to complexities with `qt` and some workaround done in conda-forge/gdal-feedstock#585, we may need to migrate all four of these at once to get a resolvable dependency path.

### CODE REVIEW

**Comment by akrherz** [comment]
Would like to see an updated dependency resolving, pardon the noise

@conda-forge-admin please rerender

**Comment by akrherz** [comment]
@conda-forge-admin please restart ci

**Comment by akrherz** [comment]
OK, reported error is:

> - package qtkeychain-0.12.0-h2264404_0 requires qt >=5.12.9,<5.13.0a0, but none of the providers can be installed

Playing with the dependencies, this combination appears to be the trouble

```
$ mamba create -n test python=3.10 "qt=5.12" pdal gdal=3.4
- package qt-5.12.1-hbfa2a6e_0 requires icu >=64.2,<65.0a0
```

Boggling

**Comment by akrherz** [comment]
OK, My strong suspicion is that a `pdal` + `gdal=3.4` + `libpq=13` build combination was missing here.  I made such a PR with conda-forge/pdal-feedstock#154, which was now merged.  We'll wait 3-4 hours for CI to build and conda-forge metadata to update and then try this again!

**Comment by akrherz** [comment]
For my own impatient sanity, linux-64 has the pdal build 18 we need here.  other arches will fail or they all will fail again if I am wrong :)

@conda-forge-admin please restart ci

**Comment by akrherz** [comment]
```
$ mamba create -n test python=3.10 "qt=5.12" pdal gdal=3.4
```
works now, so hope springs eternal...

**Comment by akrherz** [comment]
:rocket: :moon: linux-64 got past dependency resolution and is actually building at the moment, horray!  This all should hopefully be green after restarting in 4-5 hours when all arches have build 18 pdal available.  Whew!

**Comment by akrherz** [comment]
So the windows build did resolve deps with an older pdal (build 17) and ended up failing at build time (different spots depending on python version strangely). at

```
2021-12-06T20:27:35.3611803Z C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DNOMINMAX -DPROJ_VERSION_MAJOR=8 -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050800 -DQT_GUI_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DSIP_VERSION=0x041312 -DWITH_BINDINGS -DWITH_QTWEBKIT -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -I%SRC_DIR%\build\src\crashhandler\qgiscrashhandler_autogen\include -I%SRC_DIR%\build -I%SRC_DIR%\BEFORE -I%PREFIX%\Library\include -I%SRC_DIR%\build\src\crashhandler -I%PREFIX%\Library\include\qt -I%PREFIX%\Library\include\qt\QtCore -I%PREFIX%\Library\.\mkspecs\win32-msvc -I%PREFIX%\Library\include\qt\QtGui -I%PREFIX%\Library\include\qt\QtANGLE -I%PREFIX%\Library\include\qt\QtWidgets /DWIN32 /D_WINDOWS /W3 /GR /EHsc  /wd4091  /wd4100  /wd4127  /wd4190  /wd4231  /wd4244  /wd4251  /wd4267  /wd4275  /wd4290  /wd4456  /wd4457  /wd4458  /wd4505  /wd4510  /wd4512  /wd4610  /wd4706  /wd4714  /wd4800  /wd4996  /utf-8 /MD /O2 /Ob2 /DNDEBUG /showIncludes /Fosrc\crashhandler\CMakeFiles\qgiscrashhandler.dir\main.cpp.obj /Fdsrc\crashhandler\CMakeFiles\qgiscrashhandler.dir\ /FS -c %SRC_DIR%\src\crashhandler\main.cpp
2021-12-06T20:27:35.3617125Z %SRC_DIR%\build\qgsconfig.h(84): error C2001: newline in constant
...snipped...
```

Of interest is a strange PDAL error earlier

```
2021-12-06T20:24:38.9499405Z -- Found PDAL: C:/bld/qgis_1638821505425/_h_env/Library/lib/pdalcpp.lib;C:/bld/qgis_1638821505425/_h_env/Library/lib/pdal_util.lib (Process terminated due to: Exit code 0xc0000135
2021-12-06T20:24:38.9501089Z 
2021-12-06T20:24:38.9503444Z 
2021-12-06T20:24:38.9504422Z for command: %PREFIX%\Library\bin\pdal.exe --version.Process terminated due to: Exit code 0xc0000135
2021-12-06T20:24:38.9505221Z 
2021-12-06T20:24:38.9505726Z 
2021-12-06T20:24:38.9507308Z for command: %PREFIX%\Library\bin\pdal.exe --version.Process terminated due to: Exit code 0xc0000135
2021-12-06T20:24:38.9517278Z 
2021-12-06T20:24:38.9517701Z 
2021-12-06T20:24:38.9518825Z for command: %PREFIX%\Library\bin\pdal.exe --version)
```

I am unsure if build 18 will fix this or not :/  Awaiting linux-64 to be successful before starting this again as all arches now have build 18 PDAL.

**Comment by akrherz** [comment]
Status:

- Linux builds were green :partying_face: 
- Windows builds (with pdal build 17) failed due to what appears to be a `pdal.exe` segfault whilst cmake runs.  I attempted to reproduce this locally and could not, but did denote openssl flip flopping between 1 and 3 for these two releases.
- OS-X failed due to running prior to having the latest pdal build available, this was expected when I reran...

So we try again

@conda-forge-admin please restart ci

**Comment by akrherz** [comment]
Wowzers, only failures on windows (python3.7 and python3.9) both got PDAL build 17, the successful builds got build 18.  This will be good fun to track down, boggling....

**Comment by akrherz** [comment]
Looking at the resolved environments on win-64, I find

dep | python3.8 works | python 3.7 failed
--- | --- | ---
gdal: | 3.4.0-py38hc3a09ef_11|  3.4.0-py37h9ecaa47_9
libgdal: | 3.4.0-h453e081_11|  3.4.0-hd873378_9
libpq:|  13.5-hfcc5ef8_0 | 14.1-hfcc5ef8_1
numpy: | 1.21.4-py38h089cfbf_0 | 1.21.4-py37h940b05c_0
pdal:|  2.3.0-hdde07dd_18 | 2.3.0-hdde07dd_17
pkgconfig: | 1.5.5-py38haa244fe_1 | 1.5.5-py37h03978a9_1
postgresql: | 13.5-h1c22c4f_0 | 14.1-h1c22c4f_1
psycopg2: | 2.9.2-py38hd8c33c5_0|  2.9.2-py37hd8e9650_1
pyqt: | 5.12.3-py38haa244fe_8 | 5.12.3-py37h03978a9_8
pyqt-impl: | 5.12.3-py38h885f38d_8 | 5.12.3-py37hf2a7229_8
pyqt5-sip: | 4.19.18-py38h885f38d_8 | 4.19.18-py37hf2a7229_8
pyqtchart:|  5.12-py38h885f38d_8|  5.12-py37hf2a7229_8
pyqtwebengine: | 5.12.1-py38h885f38d_8|  5.12.1-py37hf2a7229_8
pyqtwebkit: | 5.212-py38h5e969cb_2|  5.212-py37h9e7b984_2
python: | 3.8.12-h7840368_2_cpython | 3.7.12-h7840368_100_cpython
python_abi: | 3.8-2_cp38 | 3.7-2_cp37m
qscintilla2: | 2.11.2-py38h5e969cb_5 | 2.11.2-py37h9e7b984_5

The postgres difference there is the obvious one, but am still debugging this more.  In the interim, in an attempt to get this green, I have pinned down postgresql to steer clear of the troublesome build 17 for PDAL

**Comment by akrherz** [comment]
This PR is now green for your consideration...

I realize it is sub-optimal to pin postgresql here, but I don't really have much more appetite to track down an obscure windows only bug and I realize this repo is treading water awaiting qt updates anyway.

**Comment by ocefpaf** [comment]
@akrherz this is awesome! Great detective work!!

**Comment by gillins** [comment]
Thanks @akrherz ! Now that https://github.com/conda-forge/qt-main-feedstock/ is available we should be able to start updating to the latest `qt`. I think `qgis` doesn't need `qtwebengine` (which isn't yet available), but will need `qtwebkit` (is this right @SrNetoChan ?).

Will look at updating `qtwebkit` to get the ball rolling....

**Comment by SrNetoChan** [comment]
@gillins not sure if we don't need qtwebengine anyway. But I guess we can start trying.
I will create PR for the newest version of qgis, based on this work in here. Let's see how it goes

**Comment by akrherz** [comment]
Just to denote that `qt-main` already had a master build timeout failure with `aarch64`, so there's no package for that arch yet.

**Comment by gillins** [comment]
Thanks @akrherz but we don't build `qgis` under non-x86_x64 yet - lots of the dependencies haven't been rebuilt for `arm` etc. Not sure what would be involved in doing this...

**Comment by akrherz** [comment]
> Thanks @akrherz but we don't build `qgis` under non-x86_x64 yet

You are so correct, I am sorry. I have my nose in more feedstocks than I should at the moment :(

**Comment by gillins** [comment]
> I have my nose in more feedstocks than I should at the moment :(

Ha ha - I'm very impressed with your energy and enthusiasm! :smile:

**Comment by SrNetoChan** [comment]
@gillins  
> Will look at updating `qtwebkit` to get the ball rolling....

We probably need pyqt to be updated as well, don't we?

**Comment by gillins** [comment]
> We probably need pyqt to be updated as well, don't we?

Good point, perhaps we should wait.

**Comment by SrNetoChan** [comment]
Probably better... No need to waste energy. I think that we need webengine to be able to update the pyqt-feedstock anyway.

**Pull request merged**
