### PR TITLE
Update to 3.10.13

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@SrNetoChan I wonder if the pins in `conda_build_config.yaml` are causing compatibility problems...?

**Comment by SrNetoChan** [comment]
Maybe, but for us pinning the LTR version would be very important. The most important dependencies should not change during the LTR lifetime.

I didn't have the chance, but I was going to try going back to the old compilers.

**Comment by SrNetoChan** [comment]
@gillins can you help me understand the dependencies errors? I was never able to understand it,neither find a place where to read about it. This is one of the dependencies errors, are all these dependencies failing? is there a way to see the available versions and the ones that are needed.

**Comment by gillins** [comment]
Sorry @SrNetoChan I can never understand these errors... @ocefpaf normally works them out - maybe he might share his understanding?
I've noticed that the `gdal` build is also failing ATM with a similar error: https://github.com/conda-forge/gdal-feedstock/pull/425

**Comment by SrNetoChan** [comment]
Not rerendering fixed the linux problems, but not the rest. So probably not a good solution

**Comment by gillins** [comment]
@SrNetoChan I've seen that same OSX .app packaging error on `master` and ended up working around it by disabling the .app generation which wasn't straightforward. Maybe something changed in `conda-build` to cause this?

Can we wait this version out and go straight to the next LTR (I think you said February?) 

I think that Windows error is related to `pyqt` still being broken there...

**Comment by SrNetoChan** [comment]
Yes, sure. Not sure if many people is following the LTR branch anyway...

**Comment by ocefpaf** [comment]
> Sorry @SrNetoChan I can never understand these errors... @ocefpaf normally works them out - maybe he might share his understanding?
> I've noticed that the `gdal` build is also failing ATM with a similar error: [conda-forge/gdal-feedstock#425](https://github.com/conda-forge/gdal-feedstock/pull/425)


Looking into it today. Without a mac it is a bit hard but let me see if I can find the problem.

PS: I'm re-kicking the CIs here just in case.

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
I guess @gillins is right, and probably the problem lies on having pinned dependencies that can't be solved. And am going to comment that for a while just to check it out, PLEASE DON'T MERGE.

**Comment by SrNetoChan** [comment]
Ok, not related with the dependency pinning. Reverting it...

**Comment by gillins** [comment]
@SrNetoChan I think you'd have to re-render after removing the pinning....

**Comment by SrNetoChan** [comment]
Uhmmm... Thank @gillins I will try that again then. With the rerendering.

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@SrNetoChan is it ok if we skip OSX for now? It is hitting that same OSX .app problem with the new conda-build. The workaround would be to backport `0007-OSX-no-app.patch` from master (and make adjustments to the activate scripts). Not sure I can find the time/enthusiasm ATM...

BTW `0007-OSX-no-app.patch` has been merged into `qgis` master as https://github.com/qgis/QGIS/pull/41001 and I hope to push all our patches upstream eventually...

**Comment by ocefpaf** [comment]
> I am a bit disappointed that we had the need to remove the local pinning. My idea for the LTR branch was to keep it as stable as possible by not bumping certain dependencies during its life cycle. But I understand now that it will be hard to do as the building machinery is also changing over time. Besides, I am still a big noob on all this, and I am not seeing any improvements on that front... So the work ends up always on you and @ocefpaf. (Thanks for your effort!)

The ideal solution would involve rebuild some of the pinned packages for the new pins that are not frozen here. I could not look into this, sorry, but if you are OK with this solutions let's not worry about it. If you want the local pinning back we need to figure out what needs rebuilding and against what version, that can be tricky.

**Pull request merged**
