### PR TITLE
update qgis to 3.26.3

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
Just to see how it goes :-)

**Comment by SrNetoChan** [comment]
I have tried to build it locally in my linux machine and it gave an error with some sip object. Maybe it's the same as before, just in linux or something different. So i decided to test it.

**Comment by izahn** [comment]
Looks like it went pretty well actually! The Linux issue looks the same as the one we hit before, basically we had to build it manually directly on a physical machine.

**Comment by SrNetoChan** [comment]
Actually they all failed...

The error appears while running sip build and looks like this:

    proto_str = proto_str.replace(name, value)

AttributeError: 'ScopedName' object has no attribute

**Comment by izahn** [comment]
> Actually they all failed...
> 
> The error appears while running sip build and looks like this:
> 
> ```
> proto_str = proto_str.replace(name, value)
> ```
> 
> AttributeError: 'ScopedName' object has no attribute

Ah yes, I know about that. Needs sip 6.7 I think. This is actually why I went with the LTR.

**Comment by SrNetoChan** [comment]
Ah, so we need to wait for sip update?

**Comment by izahn** [comment]
> Ah, so we need to wait for sip update?

sip has already been updated to 6.7, but for whatever reason 6.6.2 still gets pulled in here. You can try pinning `sip >=6.7.0` and see if the error tells you what needs to be updated for compatibility with sip 6.7

**Comment by SrNetoChan** [comment]
I have pinned sip to the newest version like you said and I got this error:

The reported errors are:
- Encountered problems while solving:
-   - package pyqtwebkit-5.15.7-py39h5a03fae_1 requires pyqt >=5.15.7,<5.16.0a0, but none of the providers can be installed


So it must be between pyqtwebkit and pyqt that needs to be updated to the newer sip. Maybe it's probably better to wait for migration?

**Comment by SrNetoChan** [comment]
This means I need to try to rebuild pyqt with forcing the new sip? then pyqt-webkit?

(taking the opportunity to learn)

**Comment by SrNetoChan** [comment]
Update SIP in PyQt worked well. Will wait for the merge then try the pyqt webkit

**Comment by SrNetoChan** [comment]
It's still picking sip 6.6.2 so I need to go back to the local build with the pinned version to find other depencies that need update.

**Comment by SrNetoChan** [comment]
Ahh interesting. Thanks @izahn 

The reason you use mamba and not conda is because mamba should be faster solving, right?

**Comment by ocefpaf** [comment]
> The error messages are often misleading unfortunately. Basically it can't install the requested versions, so it considers other versions, and then reports the error that results from that. At this point I usually just start guessing there the incompatibilities might be and then test them manually by trying to create environments with those versions.

We need that text in our docs!

**Comment by SrNetoChan** [comment]
I seem to be really bad at guessing what the incompatibilities are... :-p

 I have tried comparing the packages that get installed in qgis and the ones installed when I create an environment like @izahn suggested. 

So I tried to add packages to that environment but could not find problems.

I then tried adding qgis package to the mix 3.22 I guess), and no solving problems appeared even with sip=6.7. shouldn't that trigger the incompatibilities right away?

Or does this mean that the isssue is not with the installed packages but the ones needed to build qgis?

Sorry if this is a really stupid question.

**Comment by ocefpaf** [comment]
> I seem to be really bad at guessing what the incompatibilities are... :-p

Nope. The solver is :smile:, really. This is an open and really hard problem to solve (no pun indented). The next version of mamba will probably make our life a bit easier.

> Sorry if this is a really stupid question.

It is not. Complex packages, like qgis, are really hard to debug b/c the amount of direct and indirect dependencies is huge. Heck, anything that depends on gdal alone makes our life miserable.

Your debug logic is OK but we need to check the channels and any other constraint that may exist at build time to reproduce this correctly.

**Comment by izahn** [comment]
`qscintilla2` needs to be rebuilt for sip 6.7:

```
mamba create -d -n ales qscintilla2=2.13.3=py39h18e9c17_2 sip=6.7
```
```
Looking for: ['qscintilla2==2.13.3=py39h18e9c17_2', 'sip=6.7']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
Encountered problems while solving:
  - package qscintilla2-2.13.3-py39h18e9c17_2 requires sip >=6.6.2,<6.7.0a0, but none of the providers can be installed
```
Don't ask my how I figured that out, seems to be more an art than a science at this point...

**Comment by SrNetoChan** [comment]
Ahahah, you smelled it!

I guess with practice one starts to understand which dependencies are connected. I went brute force trying every dependency...

**Comment by SrNetoChan** [comment]
On ithttps://github.com/conda-forge/qscintilla2-feedstock/pull/46

**Comment by izahn** [comment]
We need to unpin `pyqt-builder` also.

**Comment by izahn** [comment]
I think this is good to go. Someone will need to build the Linux packages as before, I'll try to get started on that later today.

**Comment by gillins** [comment]
Shall I merge this one or go for https://github.com/conda-forge/qgis-feedstock/pull/266 instead?

**Comment by SrNetoChan** [comment]
I would say we can merge this as 3.28.0 is a release candidate

**Comment by SrNetoChan** [comment]
I will try to build the linux ones locally

**Comment by gillins** [comment]
Can we close this one @SrNetoChan ? Is LTR still 3.16.x?

**Comment by SrNetoChan** [comment]
Sure. LTR is the 3.22 now

**Comment by gillins** [comment]
> Sure. LTR is the 3.22 now

So we need to update the LTR branch manually?

**Comment by SrNetoChan** [comment]
We need to point it to the latest 3.22 commit.

**Comment by gillins** [comment]
Am I doing the right thing in this PR: https://github.com/conda-forge/qgis-feedstock/pull/275 ?

**Pull request closed without merging**
