### PR TITLE
Update LTR 3.28.11

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
Trying to update LTR without the backports (to see if it builds on windows)

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@gillins should we merge this even if there will be no update for windows users for now?

**Comment by gillins** [comment]
I'm happy for you to merge, no strong thoughts. I guess it shows how hard it is to keep updated once things aren't using the current pinning....

**Comment by SrNetoChan** [comment]
@gillins what do you think we need to move forward?

**Comment by gillins** [comment]
I don't think we can really update LTR safely without some sort of force push thing from main. Not really my area unfortunately. I think you are good to merge this for now and fix it up in the next LTR version.

**Comment by SrNetoChan** [comment]
Sorry, my bad for removing the LTR from migrations...

We still have a long way until the next major LTR (feb 2024) with monthly patch releases, so I will merge this for now, but try to fix it later to see if I can have build in windows for the following months.

**Comment by SrNetoChan** [comment]
I will pin the backports PR instead, has it fixes some stuff and close this one.

**Pull request closed without merging**
