### PR TITLE
Migration proj821 and icu69 at once, drop python3.7

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Attempting both migrations at the same time, to see if we can get around depsolver fun.

### CODE REVIEW

**Comment by akrherz** [comment]
Ah yes, we are back in the DLL hell I was working on last year, with the small dependency window with postgresql.  Bumped that and I see Azure + conda forge is busted at the moment.  Serenity now :) https://conda-forge.org/status/#ongoing_incidents

**Comment by akrherz** [comment]
trouble now is here
```
mamba create -n dev python=3.10 libgdal=3.4.1  pyqtwebkit
  - package pyqtwebkit-5.212-py36h83728eb_0 requires python_abi 3.6.* *_cp36m, but none of the providers can be installed
```

boggling

**Comment by akrherz** [comment]
My current theory is that we either have dependency trouble with `icu=69.1` or we are awaiting conda-forge/qtwebkit-feedstock#21

**Comment by izahn** [comment]
> My current theory is that we either have dependency trouble with `icu=69.1` or we are awaiting [conda-forge/qtwebkit-feedstock#21](https://github.com/conda-forge/qtwebkit-feedstock/pull/21)

I believe `qtwebkit` is the problem here. Unfortunately (https://github.com/conda-forge/qtwebkit-feedstock/pull/21 is blocked by https://github.com/conda/infra/discussions/514

If you have a Windows machine and can rebuild `qt` we can break this logjam.

**Comment by gillins** [comment]
> If you have a Windows machine and can rebuild qt we can break this logjam.

I've been trying to build it on my low end Lenovo but it keeps crashing. I think it's running out of memory. If someone has something more decent that would be great. I'll keep trying in the meantime.

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
The `qtwebkit` rebuild hasn't synced yet, try again in a few hours

**Comment by izahn** [comment]
@conda-forge-admin please restart ci

**Comment by izahn** [comment]
@conda-forge admin please restart ci

**Comment by izahn** [comment]
@conda-forge-admin please restart ci

**Comment by izahn** [comment]
OSX builds now failing with 
```
$SRC_DIR/src/core/providers/ogr/qgsogrprovider.cpp:6070:34: error: no matching constructor for initialization of 'QgsOgrDatasetSharedPtr' (aka 
'shared_ptr<QgsOgrDataset>')
```
FreeBSD hit this too, discussion and patches at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259967
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259967

**Comment by akrherz** [comment]
Eh, I am unsure how to backport that patch, so I have to punt on it.  Would it be easier to ping down llvm < 13 on os-x?

**Comment by izahn** [comment]
> Eh, I am unsure how to backport that patch, so I have to punt on it. Would it be easier to ping down llvm < 13 on os-x?

That patch is against a more recent `qgis` since we are stuck on `3.18` until we can get an updated `qt`. We would have to figure out how to backport it to `3.18`, not sure how hard that would be.

I don't know about forcing older llvm.

**Comment by izahn** [comment]
I made an attempt in https://github.com/akrherz/qgis-feedstock/pull/1 can you merge it and see if it works?

**Comment by akrherz** [comment]
Thanks @izahn , what do you think about adding a qualifier to only apply the patch on os-x ?

**Comment by izahn** [comment]
> Thanks @izahn , what do you think about adding a qualifier to only apply the patch on os-x ?

From what I understand this change is made unconditionally upstream, so it makes some sense to do the same here. On the other hand we shouldn't make changes unnecessarily. I don't have a strong feeling one way or the other.

**Comment by izahn** [comment]
@akrherz we did it! Anything else you want to change before requesting review / merge?

**Comment by akrherz** [comment]
@izahn Awesome!  Nope, its ready for merge consideration!

**Comment by gillins** [comment]
Thanks everyone!

**Pull request merged**
