### PR TITLE
meta.yaml: try to force rebuild against GDAL 3.6.2

### PR DESCRIPTION
**Pull request by rouault**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rouault** [comment]
@conda-forge-admin, please rerender

**Comment by rouault** [comment]
hum rebuild attempts still draw GDAL 3.6.1... Probably the version isn't fully "promoted" yet ? Anyway rebuilding QGIS against 3.6.2 aren't strictly required as 3.6.2 is ABI compatible with 3.6.0

**Comment by SrNetoChan** [comment]
Last time we had to rebuild PostgreSQL first so that 3.6.1 was picked up.

**Comment by gillins** [comment]
Yeah there will be something that's out of date that needs to be rebuilt to get 3.6.2. I'll try and find time later in the week to track this down.

**Comment by rouault** [comment]
> I'll try and find time later in the week to track this down.

out of curiosity, is there some command line invokation / tool to figure that ?

**Comment by gillins** [comment]
I don't know of any... I normally have to try every package in turn and see what won't install with the latest gdal.
This may prompt me to do something I've been considering for ages - write a script that runs once a day or so and:
a) notifies me if the latest qgis and gdal won't install together, and
b) tries something like the above in an automated way so we know what package is the problem.

I'm a bit out of the loop with what's happening with conda forge so it could be someone has already done something like this. Qgis can't be the only package with complex dependences that has this kind of problem semi regularly.

**Comment by SrNetoChan** [comment]
Mamba has some commands to show for a specific package, what it depends of and which itself is a dependency. Maybe useful fo find the culprits.

**Comment by gillins** [comment]
`pyproj` won't install with `gdal` 3.6.2. Attempting fix that now.

**Comment by xylar** [comment]
@gillins, gdal has migrated to proj 9.1.1.  There are issues with pyproj with this version, see https://github.com/conda-forge/pyproj-feedstock/issues/126 and https://github.com/pyproj4/pyproj/issues/1192.  So we were hoping to hold off on migrating pyproj to that version.

For now, the easiest solution might be to build gdal 3.6.2 with proj 9.1.0.

**Comment by xylar** [comment]
https://github.com/conda-forge/gdal-feedstock/pull/713 should hopefully help.

**Comment by gillins** [comment]
Indeed it does! Creating a new env seems to pick up latest qgis and gdal 3.6.2. Closing.

**Pull request closed without merging**
