### PR TITLE
Update to 2.18.17

### PR DESCRIPTION
**Pull request by SrNetoChan**
Attempt to update to 2.18.17. seemed to have worked locally.

### CODE REVIEW

**Comment by ceholden** [comment]
Thanks @SrNetoChan ! Would you be interested in being a maintainer of this recipe? I believe all that's necessary is to add your Github username to the `recipe-maintainers` section at the bottom of `meta.yaml`.

**Comment by SrNetoChan** [comment]
@ceholden I am afraid I don't have enough skills for it. I don't know much about packaging. I just copied the what was done for the 2.18.16 update.

I am also giving my first steps with conda.

But I am very interested in what needs to be done to update to QGIS 3, and to extend the recipe to Windows and Mac. :)

**Comment by ocefpaf** [comment]
> @ceholden I am afraid I don't have enough skills for it. I don't know much about packaging. I just copied the what was done for the 2.18.16 update.

This PR means you do have the skills, packaging in conda-forge is exactly that :wink:

> But I am very interested in what needs to be done to update to QGIS 3, and to extend the recipe to Windows and Mac. :)

:+1: 

Pinging @msarahan who was trying to advance the OS X packaging.

**Comment by SrNetoChan** [comment]
@ocefpaf  I can keep an eye on qgis versions and update in case of new releases.

**Pull request merged**
