### PR TITLE
cleanup qtserial and qtlocation

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Review by gillins — APPROVED** [review]

**Comment by gillins** [comment]
Are you happy to merge this @SrNetoChan ?

**Comment by SrNetoChan** [comment]
Yes sure!! If it builds, it should mean that all dependecies are satisfied,
right? Go ahead and merge.

A quarta, 8/06/2022, 23:51, Sam Gillingham ***@***.***>
escreveu:

**Comment by gillins** [comment]
I guess so - couldn't see any messages saying things weren't found. Merging.

**Pull request merged**
