### PR TITLE
pin pyqt-builder

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is intended to fix the Mac and Windows build problems in https://github.com/conda-forge/qgis-feedstock/runs/8728593385

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by ocefpaf** [comment]
Hehe. Just sent #261 but this is probably better.

**Comment by izahn** [comment]
Yeah I saw that too!

I'm optimistic about this one, comparing https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=575723&view=logs&jobId=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00 and https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=578439&view=logs&jobId=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00 shows this is one of the few differences.

One doubt -- should we bump the build number or no? Since the builds were never uploaded maybe we don't need to?

**Comment by ocefpaf** [comment]
> One doubt -- should we bump the build number or no? Since the builds were never uploaded maybe we don't need to?

Probably not necessary.

**Comment by SrNetoChan** [comment]
You guys are tireless... Thanks!

**Comment by izahn** [comment]
This is ready for review and merge.

**Pull request merged**
